### ISSUE TITLE
How to Rasa dynamic chat bot integrating with react js?

### ISSUE THREAD

**Issue by BunnyStylish** [botfront/rasa-webchat#108]
Hi everyone,
   I am creating a chat bot using rasa. Now i want to integrating that rasa chat bot with react js. How to integrate. is there any configuration. Please let me know. My exact problem is see this link once https://forum.rasa.com/t/is-it-possible-to-integrate-rasa-with-react-js-if-possible-how-to-configure/15254.
If anybody know please let me know
Thank you in advance

**Comment by MatthieuJnon** [comment]
Please read this section of the README: https://github.com/botfront/rasa-webchat#as-a-react-component
