### ISSUE TITLE
Is the initPayload not triggered in the javascript version? 

### ISSUE THREAD

**Issue by psi43** [botfront/rasa-webchat#115]
Hey, 
I've read the other questions about posting a "welcome message" at the start of the chat and followed all the steps mentioned in those. 

I am using the script-tag variance, not the React component. Does the script-tag one not support the initPayload? 

I added the following to my domain.yml: 

```
intents:
- get_started

templates:
  utter_introduction1:
  - text: Hello, how can I help you? 

actions:
- utter_introduction1
```

Then this to my stories:
```
## welcome
* get_started
    - utter_introduction1
```
(as well as several other stories, which start with *get_started and the utterance)

and my script tag includes the
```
initPayload: "/get_started",
```

As far as storage goes, the script tag is set to
```
storage: "session"
```
I also tried adding a /get_started to my NLU under the intent:get_started, but since it was never mentioned anywhere to do this, I removed it and tried that as well. 

Whenever I made a change, I executed a rasa train and a new model was created. 

Before calling the WebChat.default.init, I also tried to put a sessionStorage.clear(), but it also does nothing. 

The chatbot itself works fine, but it's just reactive, it doesn't start the conversation; the user has to do that, which isn't great. 

Is there anything I have to consider in the socketio nodejs file? Like handling the initPayload or something like that? Because I can't find information about that anywhere and it's never mentioned when other people have this problem. 

I'd really appreciate some help, thank you!

**Comment by znat** [comment]
It all seems correct. The only thing I can think of is that there's already something stored in your session and for that reason it doesn't send the initPayload. Can you try playing with the various storage options, and also see if changing the `session_persistence` param in the Rasa credentials help?

**Comment by psi43** [comment]
I'll try that on Monday, thank you very much!

**Comment by radicand** [comment]
I set `initPayload` to a text value that a user would normally have typed. E.g., `initPayload: "hello"`. This then maps back to my `greet` intent and greets the user on first interaction. It's working fine for me this way using both script and React types. Just make sure your bot response already to whatever phrase you're using in that parameter, and as mentioned above, reset your page cache/storage to check too.

**Comment by n2718281** [comment]
I have the same issue, the initPayload is not always sent.
@psi43: did you find a solution?
