### ISSUE TITLE
Incorporating the target field in addSnippet

### ISSUE THREAD

**Issue by dasxx179** [botfront/rasa-webchat#118]
Hi,

I know that it is possible to display a link with this widget and rasa in the Markdown format.  However, I would also like the functionality of having the _target parameter which exists in the original repository that this widget is forked from.  Could anyone help me out on incorporating the target parameter with addSnippet?  The overall objective is to download a CSV file by clicking on a link to the user's local machine.  Thanks!

@znat

**Comment by znat** [comment]
In progress : #117

**Comment by dasxx179** [comment]
> In progress : #117

Thanks for the reply @znat 
However, the pull request you referenced does not have any mention to targets, but references opening links in new tabs.  Did you mean to reference another request that mentions targets?  Is it safe to presume that this feature is not possible as of right now and is under development?  Thanks!

**Comment by MatthieuJnon** [comment]
If you're using Botfront, you can directly change this parameter in your bot response settings. If you're not using Botfront however, you can pass this setting in your bot response, add a metadata property, with the property linkTarget which can either be set to _blank or _self.
