### ISSUE TITLE
Deploying the rasa webchat on server

### ISSUE THREAD

**Issue by DrGardiner** [botfront/rasa-webchat#129]
Hi, 
I can run the rasa webchat successfully on localhost and it communicates correctly with my locally implemented rasa server. But the issue arises when I call the following command(same command which leads to successful connection) on server:
`npx webpack-dev-server --config webpack.dev.js --port 8000`
It says it has been compiled successfully but when I call the same port like this:
`myserverip:8000`
I don't get any result. Could you please give me a detailed instruction on how to implement it on server? (BTW, my server is Ubuntu 18.04 LTS)

In addition, when I use the `webchat-0.5.8.js` script and mimic the example you've provided I get an error like this in the browser console:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://SV-ipAddress-WAS-HERE:8080/socket.io/?EIO=3&transport=polling&t=MtLcjZT. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).`
Although I have run RASA by `rasa run --enable-api --cors "*" --debug --port 8080 --endpoints endpoints.yml` I get this CORS error!
Same command on localhost works perfectly well!
I am looking forward to hearing from you guys
Thanks in advance

**Comment by piyush29programmer** [comment]
@DrGardiner   which version of rasa are you using?

**Comment by DrGardiner** [comment]
> 
> 
> @DrGardiner which version of rasa are you using?

Hi Piyush,
I am using Rasa version 1.3.4

**Comment by piyush29programmer** [comment]
Please post the command you are using to run the action and rasa server?

**Comment by piyush29programmer** [comment]
are you using any load balancer like Nginx?

**Comment by DrGardiner** [comment]
> 
> 
> are you using any load balancer like Nginx?

I am using Apache

**Comment by piyush29programmer** [comment]
Could be try  --cors '*' instead --cors "*" for ubuntu.

**Comment by tomimartin01** [comment]
Hi!,

How could you solve it? I have the same issue, I'm using Rasa 2.6.0 and rasa-webchat 1.0.0.

Thanks
