### ISSUE TITLE
Break lines

### ISSUE THREAD

**Issue by matheusunitt** [botfront/rasa-webchat#134]
So, i'm using RASA with rasa-webchat and writing my domain with something like:
`- text: "Os serviços oferecidos pelo Centro de Informação são:\n
    1. Empréstimo de livros, periódicos e outros materias do acervo;\n
    2. Reserva e renovação de materiais; Comutação bibliográfica;\n
    3. Orientação para levantamento bibliográfico automatizado;\n
    4. Orientação sobre a normatização técnica de documentos;\n
    5. Serviços de atendimento a egressos e visitantes;\n
    6. Visitas guiadas."`

but somehow there are no line breaks. I've tried using double \n but it makes everything from the first line break to move two spaces right

**Comment by saurabh-m523** [comment]
use double space \n like so: `"This is line 1.  \nThis is line 2"`
