### ISSUE TITLE
initPayload message isn't send in the React version

### ISSUE THREAD

**Issue by tabertoz** [botfront/rasa-webchat#135]
Hi everybody
I have successfully integrated the rasa-webchat into my react website. Now I have the problem that the initPayload is not sent to the server. When I send the message manually over the rasa-webchat UI I see the response.

I have integrated the rasa-webchat over a JS function:
```
loadChatbot() {
	return (
           <Widget 
	      interval={1000}
	      initPayload={"hash_questions"}
	      socketUrl={"http://localhost:5005"}
	      socketPath={"/socket.io/"}
	      customData={{"userId": "123"}}
	      title={"Chatbot"}
	      subtitle={"Hash Questions"}
	      inputTextFieldHint={"Type a message..."}
	      connectingText={"Waiting for server..."}
	      hideWhenNotConnected={false}
	      embedded={false}
	      showFullScreenButton={false}
	      profileAvatar={botIcon}
	      openLauncherImage={questionIcon}
	      closeLauncherImage={closeIcon}
	      params={{
		images: {
		  dims: {
		    width: 300,
		    height: 200
		  }
		},
		storage: "session"
	      }}
	      customComponent={ (messageData) => (<div>Custom React component</div>) }
	    />
        )
    }
```

This function is called over the render function:
```
render() {
      return (
        <div>
          {this.loadChatbot()}	 
        </div>
      )
    }
```

Had anyone a similar problem or a possible solution?

**Comment by mofortin** [comment]
I think the initPayload is only sent during the "first" initialization -- this means that if you reload your current tab, the widget will indeed create a new connection but since it's the same browser session, the initPayload wont be send a second time. You might want to try to clear your session storage.

**Comment by tabertoz** [comment]
Unfortunately clear the session storage makes no difference. But I think it has something to do with the first initialization. Actually the rasa-webchat is on a subpage. If I switch it to the home page it works with the initPayload message.
