### ISSUE TITLE
How to get the timestamp below\besides the messages

### ISSUE THREAD

**Issue by xames3** [botfront/rasa-webchat#139]
Hello All,

I need help with integrating the timestamps from my Rasa Chatbot to the Webchat UI. I've created a tracker store which saves the conversations in a local SQLite DB. It stores the timestamp as well. Question is how am I supposed to pull that detail here in the UI. Also I'm totally novice at React and using this WebChat so a detailed explanation is appreciated. 👍

**Comment by shyam-infraon** [comment]
Pass this parameter initially when you load the widget: 
showMessageDate: true

**Comment by xames3** [comment]
Gotcha @shyam-infraon.

It worked!
Thanks!
