### ISSUE TITLE
Getting ERROR    asyncio  - Task exception was never retrieved on running command rasa run -m models --enable-api --cors "*" --debug

### ISSUE THREAD

**Issue by Prskriti** [botfront/rasa-webchat#142]
Here is the screenshot of the error message which I am getting:
![Screen Shot 2019-11-19 at 4 32 55 PM](https://user-images.githubusercontent.com/26160349/69140132-e7266e00-0ae7-11ea-8d35-09f61ceb9b23.png)

**Comment by pheel** [comment]
Rasa is complaining about a user_uttered event with no message key. Can you share 1) your Rasa version, 2) the code you use to instantiate the widget, and 3) the user behavior triggering the crash?

**Comment by Prskriti** [comment]
Using rasa 1.4.5 version: 
![Screen Shot 2019-11-20 at 10 40 07 AM](https://user-images.githubusercontent.com/26160349/69210094-af6b0500-0b7f-11ea-9ce8-4fbc0816f708.png)
Code snippet:
![Screen Shot 2019-11-20 at 10 41 12 AM](https://user-images.githubusercontent.com/26160349/69210166-e0e3d080-0b7f-11ea-880e-224e7be35087.png)
