### ISSUE TITLE
How to create docker file for this react bot

### ISSUE THREAD

**Issue by Robosensus1** [botfront/rasa-webchat#144]
Hi everyone, I creating React bot using this repository. It is working nicely in my local. For the deployment i am using AWS using docker. But here what are the files we need to write in docker file.
I am trying this way. But its not working.

```
# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install 
RUN npm install react-scripts@3.0.1 -g 

# start app
CMD ["npm", "start"]
```

Is there any problem./ Please help me .I am stuck in lot of days.
Thanks in advance

**Comment by pheel** [comment]
I'm afraid this issue is not related to rasa-webchat. I suggest you follow tutorials about deploying React apps on AWS.

**Comment by Robosensus1** [comment]
Hey thank you for replaying.I am trying above mentioned docker file but it is not working. I am asking i need any extra installations of my docker file?

**Comment by znat** [comment]
Hi, why do you need to build a Docker image for this?
In general, either you include in as a component in a react app, or you
just add the snippet to an existing html page.

Le mar. 26 nov. 2019 23 h 46, Robosensus1 <notifications@github.com> a
écrit :

**Comment by jonDel** [comment]
You can build the app and after that serve the static files generated with whatever web server you want.
I have used docker to build my app and after that I served it with nginx (as a docker instance)
My dockerfile:
´´´
# base image
FROM node:8-alpine
RUN apk add --update git
ENV PATH /usr/src/app/node_modules/.bin:$PATH
RUN git clone https://github.com/botfront/rasa-webchat.git
RUN cd rasa-webchat \
    && npm install
RUN cd rasa-webchat \
    && npm run build
´´´
Remember to copy the index.js file generated after the build and place it in your web server static files folder, along with your html/css files.
