### ISSUE TITLE
socket communication not working on server domain name

### ISSUE THREAD

**Issue by TarunKumar50** [botfront/rasa-webchat#146]
we have rasa server running on ubuntu which has private IP,public IP and domain name.
when i connect the socket via private IP it is working but over VPN , but when i connect it via domain name then it is not working.it says waiting for server.

can anyone guide me to how can i connect chatbot UI with domain name to my rasa server.

**Comment by saurabh-m523** [comment]
in case you are using NGINX, you can use the following configuration:

```
server {
  listen 80;
  listen [::]:80;

  server_name yourdomain.com;

  location / {
	proxy_pass http://localhost:5005/;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_set_header Host $host;
  }
}
```
