### ISSUE TITLE
How to change color of the chatbot?

### ISSUE THREAD

**Issue by Maadhav** [botfront/rasa-webchat#151]
How can I change the color of the chatbot i.e. instead of blue I needed to put a different color. Please help me out...

**Comment by rabinpoudyal** [comment]
Do something like this @Maadhav 
    

```
.conversation-container .header {
      background-color: #1f83e0 !important;
    }
    .launcher{
      background-color: #1f83e0 !important;
    }
    .conversation-container .client {
      background-color: #1f83e0 !important;
    }
    .conversation-container .title{
      color: #ffffff !important;
    }
```

**Comment by gargdevesh6** [comment]
@rabinpoudyal 
Where Do I need to put that code for colour change...I mean in which file? Do I need to put that code in between the script tag given on the front page of this repository or somewhere else. It would be helpful, if you can explain it in detail. Thanks

**Comment by todorGaidarov** [comment]
I think that since version 0.8 all the classes are prepended with "rw-".
The strange thing is that I cannot change background color of the client with .rw-client.
Does anybody have idea why is this happening ?

**Comment by khalo-sa** [comment]
Could anyone please point us to where we have to put our custom css files?

**Comment by MatthieuJnon** [comment]
We indeed added .rw- prefix to all of our classes to prevent interactions with styles in the outer application.
I just tested it and using .rw-client and changing the background-color works fine

**Comment by rahmahemden** [comment]
@MatthieuJnon where do i put that code ?
