### ISSUE TITLE
How to send a button with a link as payload?

### ISSUE THREAD

**Issue by Vikrant1395** [botfront/rasa-webchat#155]
Hi,
I'm using the webchat to deploy my bot made using Rasa.
I'm trying to send a button to the webchat with a link as payload.
Following is my code that I've added in my Rasa "actions.py"

![Screenshot from 2019-12-30 17-22-23](https://user-images.githubusercontent.com/55224959/71580976-18537e80-2b29-11ea-87ca-d8a9a91549a4.png)

but I get no response on the webchat widget.

following is my "index.html" for the webchat ui.

![Screenshot from 2019-12-30 17-28-10](https://user-images.githubusercontent.com/55224959/71581142-e68ee780-2b29-11ea-9743-a1de1c936a84.png)
![Screenshot from 2019-12-30 17-29-28](https://user-images.githubusercontent.com/55224959/71581224-3ff71680-2b2a-11ea-834a-83d29b6b4fa2.png)

I have tried a bunch of different ways of utterances instead of **dispatcher.utter_custom_json**, but haven't had any success.
Can anyone please help me out?

**Comment by ShirudeAkash** [comment]
have you got answer for this one, if yes then please tell
