### ISSUE TITLE
How to bring a custom text before clicking on the icon?

### ISSUE THREAD

**Issue by Maadhav** [botfront/rasa-webchat#157]
![image](https://user-images.githubusercontent.com/21285859/71680050-17338300-2daf-11ea-9611-0555be9bbaf2.png)
As you you can see the image that text is shown to make a user click. How can I set custom text for that.

**Comment by znat** [comment]
Hi, can you clarify your question?

**Comment by Maadhav** [comment]
> Hi, can you clarify your question?

Did you see the image? I also want to implement the same thing with my bot. Hey, come and chat with me. What attribute do I need to add for this?

**Comment by znat** [comment]
Right. So we're changing that, it doesn't work well. Stay tuned for the next release (0.8 probably)
