### ISSUE TITLE
Is it possible to create a card carousel using rasa-webchat?

### ISSUE THREAD

**Issue by mohitr7** [botfront/rasa-webchat#159]
If yes, then how to create a card carousel using webchat which returns images or videos in the form of a card carousel?

Can the link snippet code be used to create a card carousel, because when I tried using it to return multiple snippets it always returned a single link snippet in the form of a button?

**Comment by Swapratim** [comment]
Hi, I'm also looking for a working example of how to use card carousel in rasa.

**Comment by znat** [comment]
It's in the short term plans

**Comment by Swapratim** [comment]
Thanks Nathan for the info.

**Comment by MatthieuJnon** [comment]
You can now use carousels with the last versions
