### ISSUE TITLE
Use of emoticon

### ISSUE THREAD

**Issue by alebeta90** [botfront/rasa-webchat#161]
Hi All,

I had been using my conversation for Slack channel and using emoticons in my conversation.

Using this webchat widget the emojis from Slack are not displaying.

In Slack I will have something like `:pray:` displaying the right emoticon and in this widget I get literally `:pray:` written as part of the conversation instead of showing its emoji.

there is something I need to enable?

Thanks and all the best

**Comment by MatthieuJnon** [comment]
Hi, this way of formatting emojis is unique to Slack, it's just plain text that Slack interprets as emojis. If you want to display emojis you can use the actual unicode representation, this way they will work everywhere.

**Comment by MatthieuJnon** [comment]
See this website: https://unicode.org/emoji/charts/full-emoji-list.html
