### ISSUE TITLE
transport close

### ISSUE THREAD

**Issue by alebeta90** [botfront/rasa-webchat#166]
Hi,

some times when I chat with the bot, I can see it does not shows all the answers I should receive, but If I check Rasa X and the conversation, it is visible that Rasa sent all the messages, but for some reason it is not reflected in the webchat. When it happens I see the message in the Developer Console `transport close` and it create a new `session_confirm` and with the same `session_id` because we enable persistence.

What is is happening is there a way to avoid the Transport to close?

Thanks

**Comment by MatthieuJnon** [comment]
Can you let us know if this is still happening with the lastest versions ?

**Comment by Esteban108** [comment]
Hi, I have this issue with rasa 2.8, any solution?

**Comment by alebeta90** [comment]
Hi Esteban,

It was quite a long time ago. But I can tell you what I did.

I created myself a session that is persistent, so if the bot reconnects because the transport was close, it can pick up the right conversation. Because if the transport is closed, what it does is to create a new connection that becomes a new user when it comes to Rasa database.

So you can create your own JS code to create a persistent session id and store it in local storage, and tell rasa-webchat to run the JS to pick up the session id from local storage.
