### ISSUE TITLE
Is there anyway to send payload or message in react version?

### ISSUE THREAD

**Issue by serhiy1017** [botfront/rasa-webchat#178]
I am trying to use "Quick Reply" button outside of the rasa widget react component.
In order to do this, I think I have to send payload with socket but I can't find a function or handler which I can get socket or send payload, or even emit with socket.
So please add a props which return a function that can send payload using socket emit.

**Comment by MatthieuJnon** [comment]
Hi, there is already a method exposed to the ref that you pass to the component, attach a ref to the Widget and you should see it in `yourRef.current.sendMessage`. It takes the payload as the first parameter and an optional text to display as the second parameter.

**Comment by serhiy1017** [comment]
I want to send payload like when I click quick reply button.
For example chatbot shows a message with quick reply button: 'yes' or 'no' then you can click it in chat widget page.
But I want to trigger this event out of this widget so when I click a button out of this widget, this quick reply button can be clicked.
Is there any way to send payload for quick reply directly by using this ref?

**Comment by MatthieuJnon** [comment]
If you know the payload that you want to send, yes you can use the method to send your payload

**Comment by serhiy1017** [comment]
Can I send payload with above sendMessage function?
Can I pass payload path and quick reply button title to this function?

**Comment by MatthieuJnon** [comment]
Can you share the whole component ? Maybe try to reproduce the missing ref in a codesandbox ? Thank you
