### ISSUE TITLE
customComponent is not working with <script> webchat

### ISSUE THREAD

**Issue by srinathgnath** [botfront/rasa-webchat#190]
Hi Team,
Custom JSON sent by bot is received as null in webchat. I'm using <script> version of webchat. Let me know if I'm missing something here.

This is what i tried:
 customComponent: (message) => {
                     return "asds";
                    },
**Domain.yml**:
 utter_take_bet:
    - custom:
        Data:
              type: plain_text
              text: Select a date

**Comment by nishanNL** [comment]
customComponent will only work with React.
