### ISSUE TITLE
how to access session id?

### ISSUE THREAD

**Issue by dcsan** [botfront/rasa-webchat#191]
is there a way to get at the current session id of the chat, from the component?
do you expose any APIs or properties of the chat?

I want to use some other rasa HTTP APIs, but it needs the conversation_id
for example getting at slot values, or the current username etc.

I do see at startup the handshake for this although that looks more like session.io

```
connect:3d14088a7a44416fa3fc047e903698ce
index.js:22 session_confirm:3d14088a7a44416fa3fc047e903698ce session_id:e5a697aad51a44d6b920172017ea072e
```

I see you have a reducer, store and helper to get the session, 
https://github.com/botfront/rasa-webchat/blob/master/src/store/reducers/helper.js#L80
![image](https://user-images.githubusercontent.com/514002/75337724-5d9ede80-5842-11ea-9c6b-b3b445b04e65.png)

but wondering if you expose any of that back out of the component?
I don't want to really be doing things like `import ...` to pull your reducer into my app...

I guess I can grab it from the local storage myself but it seems a bit hacky >.<

**Comment by dcsan** [comment]
OK well I dug into all that and it looks like the session_id you have is just for socket.io or something, it doesn't relate to the rasa session_id

![image](https://user-images.githubusercontent.com/514002/75338387-7bb90e80-5843-11ea-89ef-cae34cf2efd6.png)

also when i patch into 
```
      onSocketEvent={
        {
          bot_uttered: incoming
        }
      }
```

I'm just seeing the text, no extra data

interestingly you can get other data on the convo from this type of URL

http://localhost:5005/conversations/CONVOID/tracker?token=rasa1234

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/75338648-f08c4880-5843-11ea-9f7e-32ab26f12d97.png)

which is what i want to add meta info to the bot

**Comment by MatthieuJnon** [comment]
I think by plugging into the session_confirm event with the onSocketEvent prop you should be able to get the session_id, the session_id for socket io and rasa is the same, as you can see it's persisted across sessions.

I looked at the rasa python code in the socket io channel and it appears to send the actual session_id
