### ISSUE TITLE
save and load history conversation

### ISSUE THREAD

**Issue by fabiodn** [botfront/rasa-webchat#199]
It is possible to save and load the conversation (with Rasa)?

Let's say I want to save the conversation with user A.
A logs in and chats with the bot.
A close the browser.
Next day A logs in again and see the conversation of the previous day.

So in the front end part there are functions like save/export conversation and load/import conversation?

**Comment by MatthieuJnon** [comment]
The rasa webchat saves conversations in browser storage by default, you can choose to save it either through local storage or session storage ( it will be kept longer in localStorage) please look at the readme for more details on how to choose the storage option.
