### ISSUE TITLE
Please add livechat events

### ISSUE THREAD

**Issue by harveyvandermeer** [botfront/rasa-webchat#200]
Hi,

We're working on live chat integration. The live chat server has 'livechat is typing' and 'livechat has stopped typing' events. 
1) It would be great if the rasa-webchat widget would support such events to indicate real user typing. 
2) a) Additionally it would be great if there was an extra property on a bot_uttered message to indicate not to use the messagedelay feature (it's not really helpful as it is an extra delay) 
b) Another solution could be an extra livechat_uttered event which does not trigger the messagedelay.
3) Would be great to apply customcss as well, is this an undocumented feature?

**Comment by MatthieuJnon** [comment]
Hi, the first two items are not on our roadmap but we're open to PRs. For the last item, the readme has a section with css classes you can modify to change the css.
