### ISSUE TITLE
rasa-webchat failing on deployment 

### ISSUE THREAD

**Issue by devu4** [botfront/rasa-webchat#207]
Version 0.8.0
I'm getting this error on React page load and my screen goes white and does not load. When I run it locally it works fine but we deploy using maven-frontend-plugin and I get this error:

Uncaught TypeError: Super expression must either be null or a function
    at index.js:15795
    at index.js:15794
    at Module.<anonymous> (index.js:15793)
    at n (index.js:16)
    at e.exports (index.js:52)
    at Object.<anonymous> (index.js:6)
    at f ((index):1)
    at Module.808 (HelpDrawer.js:126)
    at f ((index):1)
    at Object.303 (main.94d05bc7.chunk.js:1)

**Comment by ankan97dutta** [comment]
Has anybody solved this?

**Comment by ankan97dutta** [comment]
@charlesj @schemeway @gausie

**Comment by davidgeorge4** [comment]
Not solved yet, I assume it is a problem with packaging application. I just forked the application then took the source and directly imported into my application. Not the best solution.

**Comment by ankan97dutta** [comment]
In my case, I removed the node_modules reordered the super expression and it worked. I think I created cyclic dependency.

**Comment by Jainu-s** [comment]
@ankan97dutta  how to deploy rasa chatbot in the website? I'm trying to find the ways but I couldn't find the way. Can you please help me solve this issue?

**Comment by ankan97dutta** [comment]
@Jainu-s I installed it with npm and used it as a react component.

**Comment by MatthieuJnon** [comment]
Are you still having this issue @ankan97dutta ? Sorry for the late reply

**Comment by ankan97dutta** [comment]
@MatthieuJnon no issues anymore.
