### ISSUE TITLE
Webchat stucks on "Waiting for server..." if used in embedded form

### ISSUE THREAD

**Issue by cowjen01** [botfront/rasa-webchat#216]
I found out that from version `0.7.17` webchat stucks on `Waiting for server...` if you use embedded form inside of React component. If `embedded` is disabled everything works fine. In version `0.7.16` there is no bug at all.

<img width="1202" alt="Screenshot 2020-04-10 at 19 05 44" src="https://user-images.githubusercontent.com/6173850/79008736-54ea3980-7b5e-11ea-8f64-60c38614f278.png">

React components:

```js
const CustomWidget = () => {
  return (
    <Widget
      socketUrl="http://localhost:5005"
      socketPath="/socket.io/"
      embedded
      hideWhenNotConnected={false}
    />
  );
};
```

```js
render() {
    const { classes } = this.props;
    return (
      <Card className={classes.root}>
        <CustomWidget />
      </Card>
    );
  }
```

Console output on connect:

```
connect:8c1170bca2254f379e090b55027c7ab0
session_confirm:8c1170bca2254f379e090b55027c7ab0 session_id:4b161c35d09141e4b5e2fc1b90fc4577
```

Rasa credentials.yaml:

```yaml
socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true
```

**Comment by MatthieuJnon** [comment]
Hi, sorry for the very late reply, are you still having this issue ? We mostly use it as an embedded component and we never had such issues. Please let me know

**Comment by seanlee7891** [comment]
Hi, I have a similar issue, the webchat stucks on "Waiting for server..."  when the embedded is true and browser window size is small.
