### ISSUE TITLE
want to show carousel in google assistant

### ISSUE THREAD

**Issue by jehanzaib12** [botfront/rasa-webchat#218]
res = {
								"payload": {
									"google": {
										"expectUserResponse": True,
										"richResponse": {
											"items": [
												{
													"simpleResponse": {
														"textToSpeech": "Here are list of deals"
													}
												},
												{
													"carouselBrowse": {
														"items": [
															{
																"title": j["title"],
																"openUrlAction": {
																	"url": "https://www.bigbang.pk/"
																},
																"description": j["sub_title"],
																"footer": j["offer_description"],
																"image": {
																	"url": "http://165.227.69.207:9001/{}".format(
																		imgurl),
																	"accessibilityText": response_offer_description
																}
															},

														]
													}
												}
											]
										}
									}
								}
							}
							dispatcher.utter_custom_message(res)
							print(res)

I failed to show the carousel in google assistant

**Comment by MatthieuJnon** [comment]
Hi, we do not support the google assistant format, please use a rasa or facebook format
