### ISSUE TITLE
How to create dropdown box?

### ISSUE THREAD

**Issue by K0307** [botfront/rasa-webchat#222]
How to create dropdown list of dynamic values?  How to add the support for dropdown message in this UI?

**Comment by ankan97dutta** [comment]
Any update on this? Or checkbox as custom component?

**Comment by ankan97dutta** [comment]
Use a custom component and render it.

**Comment by K0307** [comment]
I didn't get it @ankan97dutta . Can you please elaborate it?

**Comment by ankan97dutta** [comment]
I've created a custom component which takes a list as prop and used it with

**Comment by K0307** [comment]
Okay. Thanks for response.

**Comment by MatthieuJnon** [comment]
Hi, sorry for the late reply, we can't support every type of message, but as @ankan97dutta suggested, you can use a custom component for those missing functionalities.

**Comment by tolgaduzenli** [comment]
> I've created a component multiselect which takes data as prop and used customComponent attribute of the Widget `customComponent={(message) => (message.select ? <MultiSelect data={message.select} send={send} /> : <div> </div>)}`

Hi @ankan97dutta If possible can you share your full code? I am looking for example for custom component.

Thanks,
