### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by tharinduac** [botfront/rasa-webchat#223]
Firstly i installed node modules by running "npm install".Then i run "npm start".But it doesnt work.Actually how to run this project?

**Comment by MatthieuJnon** [comment]
Hi you can run it using one of the two ways described in the README, either through a react app or through a script in an html page.
If you want to just run the react component for development purposes however you can `npm install` then `npm run dev`

**Comment by poojasingh-code** [comment]
After npm install I wrote npm run dev, it gave me missing script error , the I wrote npm run, then nothing happened, my cursor moved to next command line, how to access the project in dev env like by what url?
