### ISSUE TITLE
First message by the bot

### ISSUE THREAD

**Issue by gargdevesh6** [botfront/rasa-webchat#225]
How to make the bot utter first message instead of the user? I mean I want to replicate what is shown on the frontpage gif of this repository...1) (Hey come and chat with me) message at the bottom before opening the bot....and 2) Welcome message by the bot first without user typing anything. Thanks in advance

**Comment by gurtajs4** [comment]
Hi @gargdevesh6 

Please define an intent in domain.yml as "greet_as_bill_assistant"  and then add **initPayload** 
as below example

    <script src="https://storage.googleapis.com/mrbot-cdn/webchat-latest.js"></script>
    <script>
        WebChat.default.init({
            initPayload: "/greet_as_bill_assistant",
            ....
        })
    </script>

**Comment by gargdevesh6** [comment]
Thanks @gurtajs4 

I already got the same answer from somewhere else and it is working fine for me
