### ISSUE TITLE
Close method does not work - WebChat.close();

### ISSUE THREAD

**Issue by Junior-Shyko** [botfront/rasa-webchat#229]
Would anyone know to tell me what's going on with the close method?

When it starts with the closed content, it is completely unconfigured, it is as if the closing method was not working. The other methods of the api are ok here for me.

but if you click on the icon, the method works normally

![Captura de tela de 2020-04-30 12-28-46](https://user-images.githubusercontent.com/7341117/80729329-7d6eaf00-8ade-11ea-9b67-f9a4a910defa.png)

**Comment by MatthieuJnon** [comment]
The close method only work if you have the whole webchat open I think. On your screenshot the webchat is closed, what is open here is the tooltip which wbchat.close() can not close.
