### ISSUE TITLE
expose `toggleConversation` to the hosting page with js

### ISSUE THREAD

**Issue by amn41** [botfront/rasa-webchat#23]
related to #16 

In order to achieve the same behaviour as when a user clicks on the Launcher, it would be awesome to have access to the `toggleConversation` function as well. Would you be open to that?

**Comment by znat** [comment]
Hey @amn41, `WebChat.toggle()`, `WebChat.isOpen()`, `WebChat.isVisible`   already exposed

**Comment by amn41** [comment]
thanks @znat  - as far as I can tell though, `WebChat.toggle` just toggles whether the window is open, and doesn't call the actually `toggleConversation` function which triggers the `initPayload` . Should it?

**Comment by znat** [comment]
@dliuproduction?

**Comment by amn41** [comment]
@dliuproduction @znat I'm happy to take a look at this if you point me in the right direction :)

**Comment by znat** [comment]
@amn41 I think this is going to be de facto fixed with #24
