### ISSUE TITLE
Waiting for server

### ISSUE THREAD

**Issue by Sord27** [botfront/rasa-webchat#232]
Good evening! Try to install botfront pack.
External server, not local host. All OK, but when use http (for example http://site it connect. If I use https (https://site - waiting for server.
I use nginx with ssl certificates, proxy. Certificate from clouflare. All work but with https not connect. Who knows this?
Thanks.

**Comment by MatthieuJnon** [comment]
Hi, sorry for the late reply, any errors in the console ? What about the logs on Rasa side ?
