### ISSUE TITLE
 Can I set rasa-webchat live chat with the website host username as sender_id?

### ISSUE THREAD

**Issue by solyarisoftware** [botfront/rasa-webchat#233]
Hi, that's maybe a change request/info request:

I want to integrate a live chat into an existing website that users can navigate with or without logging-in.

Optimally I want to manage two different scenarios: 

1. user could chat with a RASA backend assistant through the live chat, even if not (yet) logged for general info, etc. 

2. But the basic requirement is that user must **log in the website with his credentials (`username`/password)** and afterward he can chat with the RASA assistant backend as a logged-in user with a single `user_id` (say the `username` == his email). In that way the assistant can profile/personalize answers. 

Reading the RASA connectors guide: https://rasa.com/docs/rasa/user-guide/connectors/your-own-website/ I understand that I can configure RASA to accept socketio channel and a good candidate for the websocket live chat integrations seems the project:
 https://github.com/botfront/rasa-webchat

My question is about how to possibly simply configure the `sender_id` equal to the `username` with rasa-webchat.

The integration seems seamless in case of an "impersonal" chat , and as I well understood, in this case the sender_id is set with a random value. That's ok for the case (1) 

But how can I manage the case (2)? Reading https://github.com/botfront/rasa-webchat#rasa, seems to me that te solution is to build a custom connector to manage `customData={{sender_id: 'aUserName'}}`. Is it so?

I wish that when user is logged in, his username is used as sender_id could be used utomatically in the `WebChat.default.init`javascript request.   

Any idea?

Thanks<br>giorgio

**Comment by n2718281** [comment]
A solution is to use the initPayload of the webchat and to parse an entity to it.
`initPayload: "/get_started{"username"= "foo", "password"="bar"}`
Then you can affect slots "username" and "password" in rasa and use them.

**Comment by solyarisoftware** [comment]
thanks @n2718281, I was referring to `sender_id`, but my final goal is to identify logged user, so your proposal makes sense!

**Comment by MatthieuJnon** [comment]
Hi, I think @n2718281 is the best idea here. We don't have a feature to add your own id in the webchat yet, it sounds like a good idea though. I'll discuss it with the team.

**Comment by MatthieuJnon** [comment]
Ok, so you either can pass the sender_id to rasa via the custom data, but as you stated in your initial messages, this will necessitate you writing your own rasa channel.
Or you can do as suggested and the data to the initial payload.
We're not planning to add a sender_id props as it will provide no additional feature compared to just adding it in the custom_data.
Thank you
