### ISSUE TITLE
using font awesome issue

### ISSUE THREAD

**Issue by FirstSuns** [botfront/rasa-webchat#238]
Hi,
I am going to use font awesome on webchat.
yarn add font-awesome
and then adding  import 'font-awesome/css/font-awesome.min.css'

https://prnt.sc/shll82

I tried several times to config loader using several way on webpack. but I always get errors.
what is the problem?
----------------------this is your webpack.dev.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  // entry: ['babel-polyfill', './index.js'],
  entry: './index.js',
  output: {
    path: path.join(__dirname, '/lib'),
    filename: 'index.js',
    library: 'WebChat',
    libraryTarget: 'umd'
  },
  devServer: {
    stats: 'errors-only',
    host: process.env.HOST, // Defaults to `localhost`
    port: process.env.PORT, // Defaults to 8080
    open: true, // Open the page in browser
    contentBase: path.resolve(__dirname, '/lib')
  },
  resolve: {
    extensions: ['.js', '.jsx']
  },
  mode: 'development',
  devtool: 'eval-source-map',
  module: {
    rules: [{
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    }, {
      test: /\.scss$/,
      use: [
        { loader: 'style-loader' },
        { loader: 'css-loader' },
        {
          loader: 'sass-loader',
          options: {
            includePaths: [path.resolve(__dirname, 'src/scss/')]
          }
        }
      ]
    }, {
      test: /\.(jpg|png|gif|svg)$/,
      use: {
        loader: 'url-loader'
      }
    }]
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Web Chat Widget Test',
      filename: 'index.html',
      inject: false,
      template: 'dev/src/index.html',
      showErrors: true
    })
  ]
};

**Comment by MatthieuJnon** [comment]
Hi, this issue is unrelated to the rasa webchat. More over the screenshot you're sharing on the issue could not be more clear. You're indeed missing a loader for css files here. Look up "how to load css files with webpack" on google. Also read the documentation on webpack loaders. Thank you, hope you're gonna figure it out
