### ISSUE TITLE
WebChat always stores conversation in localStorage

### ISSUE THREAD

**Issue by stevenbal** [botfront/rasa-webchat#244]
I have initialized the WebChat as follows:
```javascript
WebChat.default.init({
    selector: "#webchat",
    initPayload: initPayload,
    interval: 1000,
    customData: customData,
    socketUrl: socketUrl,
    title: "Gem",
    subtitle: "Je online hulp van de gemeente",
    inputTextFieldHint: "Typ hier je vraag...",
    onSocketEvent: onSocketEvent,
    connectingText: "Even geduld",
    profileAvatar: "static/img/avatar.png",
    showCloseButton: true,
    fullScreenMode: false,
    storage: "session",
    customMessageDelay: (message) => {
        let delay = message.length * 20;
        if (delay > 2 * 1000) delay = 2000;
        if (delay < 500) delay = 500;
        return delay;
    }
})
```

The issue is that the widget seems to store the conversation state in `localStorage`, even though I configured it as `storage: session`:
![Screenshot from 2020-05-22 16-26-33](https://user-images.githubusercontent.com/29249171/82678039-38571c00-9c49-11ea-9e1b-65afc84a77d7.png)

I'm using Firefox 76.0.1, if it matters

**Comment by krupal56** [comment]
user localStorage.clear(); in <script>

**Comment by stevenbal** [comment]
I have found the solution, it turns out I needed to specify `params: {storage: "session"}`, instead of just `storage: "session"`. I was confused, because in the github readme, it looked like the latter was the correct way to define it.
![Screenshot from 2020-05-26 09-58-22](https://user-images.githubusercontent.com/29249171/82875286-7ef19280-9f37-11ea-802c-23e80419a7a5.png)

**Comment by DarkGigaByte** [comment]
I had the same problem and tried the solution from @stevenbal. Seems to be working just fine. Maybe it is just not documented properly?

**Comment by MatthieuJnon** [comment]
The documentation was indeed misleading, the README has been updated to reflect where the storage option should be set.
