### ISSUE TITLE
Widget not loading, getting error

### ISSUE THREAD

**Issue by sibbsnb** [botfront/rasa-webchat#247]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.

<div id="webchat"/>
<script src="https://storage.googleapis.com/mrbot-cdn/webchat-latest.js"></script>
// Or you can replace latest with a specific version
<script>
  WebChat.default.init({
    selector: "#webchat",
    initPayload: "/get_started",
    customData: {"language": "en"}, // arbitrary custom data. Stay minimal as this will be added to the socket
    socketUrl: "http://localhost:5006",
    socketPath: "/socket.io/",
    title: "Title",
    subtitle: "Subtitle",
  })
</script>

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mu (webchat-latest.js:95)
    at p (webchat-latest.js:95)
    at m (webchat-latest.js:95)
    at webchat-latest.js:95
    at Ha (webchat-latest.js:95)
    at Ss (webchat-latest.js:95)
    at mu (webchat-latest.js:95)
    at du (webchat-latest.js:95)
    at iu (webchat-latest.js:95)
    at webchat-latest.js:95

**Comment by snehalsabale** [comment]
I Have Also observed same issue. It was running smoothly suddenly i am getting this issue.

**Comment by snehalsabale** [comment]
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.
> 
> <script src="https://storage.googleapis.com/mrbot-cdn/webchat-latest.js"></script> // Or you can replace latest with a specific version <script> WebChat.default.init({ selector: "#webchat", initPayload: "/get_started", customData: {"language": "en"}, // arbitrary custom data. Stay minimal as this will be added to the socket socketUrl: "http://localhost:5006", socketPath: "/socket.io/", title: "Title", subtitle: "Subtitle", }) </script>
> Uncaught Error: Minified React error #130; visit [https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=130&args%5B%5D=null&args%5B%5D=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
> at Mu (webchat-latest.js:95)
> at p (webchat-latest.js:95)
> at m (webchat-latest.js:95)
> at webchat-latest.js:95
> at Ha (webchat-latest.js:95)
> at Ss (webchat-latest.js:95)
> at mu (webchat-latest.js:95)
> at du (webchat-latest.js:95)
> at iu (webchat-latest.js:95)
> at webchat-latest.js:95


In my case it gets solved by clearing cache

**Comment by MatthieuJnon** [comment]
Clearing cache does solve the issue here, The format of data kept in localStorage changes over different versions. We are currently experimenting with different solutions to that problem for future releases.

**Comment by rabinpoudyal** [comment]
change localstorage to session storage like this:

params: { "storage": "session" }

**Comment by MatthieuJnon** [comment]
Hi, concerning this issue we've added a mechanism that automatically wipes the webchat local storage when it's loaded with a new version. In effect, this will make sure this issue never arise again. Sorry for the inconvenience. I'm going to close the issue now.
