### ISSUE TITLE
"\n" not working in webchat but working in rasa x 

### ISSUE THREAD

**Issue by Nishthavan** [botfront/rasa-webchat#249]
The endline or newline is not working in the rasa-webchat whereas it is working in rasa x can anyone help me with this I want the bot to respond using multiline answers

**Comment by Nishthavan** [comment]
never mind I got the solution 
use double space \n like so: "This is line 1. \nThis is line 2"

**Comment by jaimeteb** [comment]
> never mind I got the solution
> use double space \n like so: "This is line 1. \nThis is line 2"

What do you mean with "double space"? I have the same issue and can't solve it with this solution.

**Comment by Nishthavan** [comment]
I meant when you want to go to next line normally we just out a "\n" but it
works for RasaX but it was having problems with Rasa webchat so you have to
use double spaced before like "  \n" and it works. I hope this helps.

**Comment by shashwat3057** [comment]
@Nishthavan Using double space before \n worked well. Thanks.
