### ISSUE TITLE
How to increase the size of the chat windows?

### ISSUE THREAD

**Issue by Diwahars** [botfront/rasa-webchat#25]
Is there any way to increase the size of the chat window. I wanted to increase its width in a website.

How to increase it?

**Comment by znat** [comment]
ATM it's only possible if you import it as a React Component. Otherwise, it's either fullscreen/default-size.
That being said, we're open to PR's

**Comment by dliuproduction** [comment]
The css styles are listed in the README, you can add your custom styles to override the style classes accordingly.

**Comment by jonDel** [comment]
A button to toggle between widget and full-screen mode would be a wonderful feature.

**Comment by znat** [comment]
@jonDel indeed. Would you consider contributing with a PR?
