### ISSUE TITLE
Can anyone tell me how to deply this on heroku 

### ISSUE THREAD

**Issue by Nishthavan** [botfront/rasa-webchat#257]
I want to know how to deploy rasa webchat on heroku

**Comment by MatthieuJnon** [comment]
You can't deploy the webchat itself, you have to put it either on an HTML page or in a javascript or React app. then follow the Heroku guidelines for deploying HTML, javascript or React.

**Comment by Nishthavan** [comment]
And where might those guidelines be ? Can u share a link. And I have made a website of course for the chatbot but couldn't figure out how to deploy

**Comment by Nishthavan** [comment]
Because there are different servers running of Rasa I couldn't figure it out
