### ISSUE TITLE
Multiple Payload

### ISSUE THREAD

**Issue by diego-vieira** [botfront/rasa-webchat#264]
Just saw some interesting feature that could be interesting for the widget.

This instance offer a few different payloads with title and a message.

Happy to contribute if that's something you guys would like to add to the core.

![image](https://user-images.githubusercontent.com/930792/86892540-4cbb7f00-c0f8-11ea-9249-0593dc87e4b3.png)

**Comment by MatthieuJnon** [comment]
You could send an initial message with three buttons, there is no limit to the amount of text you can write in a button. I think this would have the same functionality as this. What do you think ?
