### ISSUE TITLE
How to get actual url

### ISSUE THREAD

**Issue by gdsad** [botfront/rasa-webchat#269]
I am using the Rasa-Webchat widget to deploy a virtual assistant in a website.
It is a chatbot designed to buy products.
On the website where the chatbot is hung, there is also a virtual store, where the user can browse through each existing product.

Is there any way to get the url of the product that the user is currently viewing at the time of writing in the webchat?
By doing so, I could get more data about the context of the message, knowing which product the user is currently looking at.

**Comment by MatthieuJnon** [comment]
Hi, you could infer it yourself and pass it to the customData props. This way it will be attached to socket communications.

**Comment by gdsad** [comment]
Thanks for your quick answer.
How could I infer it? 

> ... pass it to the customData props.
This could be done setting this prop in:

`<script>
  WebChat.default.init({
    selector: "#webchat",
    ...
    customData: {"actual_url": url_detected}
    ...
  })
`
?

Thanks in advance

**Comment by MatthieuJnon** [comment]
You can get the url using `window.location.href` Then yes you can pass it to the customData like you said.
