### ISSUE TITLE
Rasa Web chat customizing buttons position

### ISSUE THREAD

**Issue by yckiong** [botfront/rasa-webchat#270]
Hi, I want to reposition the web chat buttons to left. Is there any way to do it?

**Comment by MatthieuJnon** [comment]
No sorry, you can add you own css to do it though.  You probably have to look around the .rw-widget-container class, try and change itspositioning properties. You're most definitely gonna run into issues with the tooltip if you use it though.
If you figure out some good css to put the webchat on the left, we're accepting PRs. Thank  you
