### ISSUE TITLE
LocalStorage cross-domain availability

### ISSUE THREAD

**Issue by alebeta90** [botfront/rasa-webchat#271]
Hi friends,

I would like to know if it is currently possible or if there is a method to create persistent sessions among different domains. 

In my case I want to talk to users in my main domain example.com do some registration and then speak with them in another page which is a subdomain of example.com.

I was thinking that it may be possible to run a JS code that override the senderid(sessionid) inside of my subdomain , to use the same ID that user got at the registration moment. But dont know if it will work.

If someone could share experience related this topic would be useful.

thanks and all the best

**Comment by MatthieuJnon** [comment]
Hi, I think your safest bet here is to save what's in `localStorage.chat_session` after the desired step of the conversation and pass it somehow (using this api https://blog.teamtreehouse.com/cross-domain-messaging-with-postmessage maybe) to the other domain, then make sur you overwrite the `localStorage.chat_session`  before initializing  the rasa webchat

**Comment by MatthieuJnon** [comment]
Let me know if this helped you.
