### ISSUE TITLE
Deploy webchat widget with ngrok

### ISSUE THREAD

**Issue by NielsRogge** [botfront/rasa-webchat#273]
So, I built a Rasa chatbot, and included it into my website using the widget from this repository. I also built a custom action server (`action.py`). In short, my architecture is the following:

* Flask server: running at localhost:5000
* Rasa server: running at localhost:5005 (this is the socket URL)
* Rasa action server: running at localhost:5055

When I open up my web browser and go to localhost:5000, I can see my website with the chat widget in the bottom right, and the chatbot works fine.

However, when I want to deploy this website with ngrok to the internet by typing `ngrok http 5000`, the widget is not shown. Which command should I run in order to deploy my website that includes this widget?

BTW, all my code is open-source and can be found [here](https://github.com/NielsRogge/rasa-chatbot).

**Comment by MatthieuJnon** [comment]
Hi, I didn't look at your website, but the rasa webchat socket should point to the rasa instance. If you used localhost it will work from your machine obviously, but it won't work from anywhere else, meaning your rasa instance also has to be exposed to the outside world.

**Comment by NielsRogge** [comment]
Thank you for the quick reply. It works as you suggested. Here's the workflow:

First, you have to start the Rasa action server by typing `rasa run actions`. 
Then, in another command prompt window, start your Rasa server (in my case this is done by typing `rasa run -m models --enable-api --cors "*" --debug`). This will start the Rasa server at http://localhost:5005. 
Then, in another window, you have to run `ngrok http 5005`, to deploy the Rasa server to the internet.
Next, you have to replace the `socketUrl` value of the webchat widget to the ngrok address you just created.
Finally, you can start the Flask server by running `python app.py`. If you want to deploy this web server to the internet, you have to (again in another window) run `ngrok http 5000 --region eu` (as the Flask server runs at port 5000). The reason I included another region is because ngrok only allows for a single port per region in the free version.
