### ISSUE TITLE
Add Input validation 

### ISSUE THREAD

**Issue by quixote15** [botfront/rasa-webchat#277]
When creating bots we often stumble in a use case where we need to validade ones inputs or add masks to common fields such as phone, email, etc. This improves user experience and helps when there is some business logic combined with the bot.

I would like to suggest the creation of a optional params that enables input validation and maybe even input customization.

I have been thinking about this and I am gonna try to fork and implement this on a project but would this feature be welcome as a PR? What do you think?

**Comment by MatthieuJnon** [comment]
Hi, to handle validation, if your bot is using rasa, you can create [forms](https://rasa.com/docs/rasa/core/forms/#validating-user-input) in Rasa, we do not plan on adding this feature on the client side.
If you're using the webchat with Botfront, [this feature](https://botfront.io/blog/a-no-code-approach-to-rasa-forms-form-action-and-form-policy) is about to be shipped in the open source version in the following weeks
