### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 

### ISSUE THREAD

**Issue by zusibell** [botfront/rasa-webchat#279]
Hi! 

I have been working with rasa-webchat widget and I am using the source: https://storage.googleapis.com/mrbot-cdn/webchat-latest.js 

Everything was working fine yesterday but suddenly I got an access error: Failed to load resource: the server responded with a status of 403 ()

How can I solve this?

Thank you!

**Comment by pk-pk** [comment]
I had the exact same error, i was working with the same source as mentioned above,

Today when i checked the README.md on github, i came to know that the link " https://storage.googleapis.com/mrbot-cdn/webchat-latest.js" was changed to "https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.min.js"

I tried with the new link too, but nothing seems to be happening, 
> there is no visible chat bot window, 
> no error on the console, 
> there is a log for timeout, which points to the file "_index.min.js:formatted:33822_"

This is what i have written in the body of my website.


```
<div id="webchat"></div>
<script src="https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.min.js"></script>

<script>
  WebChat.default.init({
    selector: "#webchat",
    initPayload: "/get_started",
    customData: {"language": "en"},
    socketUrl: "http://localhost:5005",
    socketPath: "/socket.io/",
    title: "VIronica",
    subtitle: "Virtual Assistant",
    params: {"storage": "session"}
  })
</script>
```


**Please let us know how can this be resolved ASAP?**

Thank you.

**Comment by MatthieuJnon** [comment]
hi, sorry for the mixup, we changed from providing the webchat ourselves to using a cdn.
As shown here : https://github.com/botfront/rasa-webchat#in-a-script-tag
Here is the new link: https://github.com/botfront/rasa-webchat#in-a-script-tag
