### ISSUE TITLE
Invalid hook call violation with latest React

### ISSUE THREAD

**Issue by sebwe** [botfront/rasa-webchat#282]
I've created basic React app with Rasa-WebChat. Here is my **package.json**:

```{
  "name": "test-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "rasa-webchat": "^0.11.5",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-scripts": "^3.4.3",
    "typescript": "~3.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

and the main **App.tsx** file:

```
import React from 'react';
import './App.css';
import { Widget } from "rasa-webchat";

const App = () => {
  return (
    <div className="App">
      <Widget
        socketUrl={"http://localhost:5005"}
        socketPath={"/socket.io/"}
      />
    </div>
  );
}

export default App;
```

When I try to run the tests all the tests are failing due to the Invalid hook call violation:

`Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Any ideas how to solve it? Tried with different React versions, without any results...

**Comment by MatthieuJnon** [comment]
Hi, this issue is usually caused by you having several react versions in your app at the same time. Here it looks like react is imported from react but also from react-scripts. I think you should investigate around that.
But I don't think the issue is related to the webchat here. Let me know if you found a solution

**Comment by sebwe** [comment]
Thanks for the hint, but the application is not compiling without the react in deps. I tried also to force the same react as is used by react-script (with `yarn resolutions`), but it didn't help either. Still looking for a solution...

**Comment by MatthieuJnon** [comment]
ok so you're using yarn ? Might be the issue, can you provide a full project where the bug is replicated ?

**Comment by sebwe** [comment]
Sure thing. Here is the repo with this simple app:  `https://github.com/sebwe/rasa-webchat-test`.

To reproduce the error execute `yarn test`.

**Comment by stephanrb3** [comment]
I'm having the same problem.
