### ISSUE TITLE
Modify the sender_id for manage the session according to Django session

### ISSUE THREAD

**Issue by PassionatePriyanka** [botfront/rasa-webchat#287]
Hi,

How can I modify the sender_id using customData or any other way to manage the rasa chatbot session according to Django session.

After integrating django with rasa chatbot, on clearing the session of the django page, the rasa chat does not reload its session (Rasa), session remains same for all users on same tab… Kinldy assist us, in solving the issue…

Also we used django for user login to the webhcat session, if there is possible to get django session_key as sender id, so that we can feel easy to find who used the session Kindly guide us… 

Thanks in advance

**Comment by MatthieuJnon** [comment]
Hi can you add an arbitrary id in the customData prop and it should be passed down to rasa.
For clearing sessions on the same browser you can manually clear the local storage of the user when he deconnects using `window.localStorage.removeItem('chat_session');`

**Comment by PassionatePriyanka** [comment]
I am new in rasa. I can you help me with how can I passed customData prop to rasa

**Comment by alebeta90** [comment]
Hi @PassionatePriyanka 

I did work integratin the widget with Django, I did something similar as @MatthieuJnon mentioned before.

you could just update the localstorage with the session ID you want. Just need some javascript work in order to accomplish that
