### ISSUE TITLE
Webchat opens in full screen mode in web page run in apache environment

### ISSUE THREAD

**Issue by Fugit185** [botfront/rasa-webchat#288]
Hi, 

Webchat runs only in full screen mode, not as a normal chatbot widget. 

When I run it in my other Virtualbox virtual environment, without docker and without apache2, it works normally. I 
doubleckick index.html and it opens in firefox tab, there it is as chatbot widget. In apache 
environment I go to webpage www.usera.com, see config files below, and there it opens as full screen 
mode

I use virtualhosts in apache2. Version is 2.4.29(Ubuntu)  
Here are my config files  

_linttu@linttu-VirtualBox:/etc/apache2/sites-available$ cat userA.conf_

<VirtualHost *:80>
         ServerAdmin webmaster@localhost
        ServerName usera.com
        ServerAlias www.usera.com
        DocumentRoot /home/userA/public_html/
        <Directory /home/userA/public_html/>
           Options Indexes FollowSymLinks
           AllowOverride None
           Require all granted
        </Directory>
                          ErrorLog ${APACHE_LOG_DIR}/error.log
                          CustomLog ${APACHE_LOG_DIR}/access.log combined
                          #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

_linttu@linttu-VirtualBox:/etc/apache2/sites-available$ cat /home/userA/public_html/index.html_

<html>

    <head> 

        <title>Webchat</title>

    </head>

    <body> 
 
        <div id="webchat"></div>
        <script src="https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.min.js"></script>
        // you can add a version tag if you need, e.g for version 0.11.5
        https://cdn.jsdelivr.net/npm/rasa-webchat@0.11.5/lib/index.min.js
        <script>
           WebChat.default.init({
                selector: "#webchat",
                initPayload: "/get_started",
                customData: { "language": "en" }, // arbitrary custom data. Stay minimal as this will be added to the socket
                socketUrl: "http://localhost:5005",
                socketPath: "/socket.io/",
                embedded: true,
                title: "Welcome",
                subtitle: "to my chatbot",
                params: { "storage": "session" } // can be set to "local"  or "session". details in storage section.
            })
        </script>
    </body>
</html>

**Comment by MatthieuJnon** [comment]
Hi, I think it's because you are using `embedded: true`, this lets the webchat take all the space available in it's enclosing component. Set it to false or don't set it at all and it should resolve your issue

**Comment by Fugit185** [comment]
> Hi, I think it's because you are using `embedded: true`, this lets the webchat take all the space available in it's enclosing component. Set it to false or don't set it at all and it should resolve your issue

Thanks, it was that. I thought that embedded means that it is "embedded" 
Thank you very much
-Pauli

**Comment by MatthieuJnon** [comment]
It is indeed embedded in its parent component, it's true that the readme description isn't very clear about what it means
