### ISSUE TITLE
Webchat widget doesn't open in Azure server

### ISSUE THREAD

**Issue by Fugit185** [botfront/rasa-webchat#291]
I can run my webchat widget in my Virtualbox environment but with exactly same configuration it doesn't run in Microsoft Azure server. Both enviroments are: Ubuntu 18.04, Rasa running in docker and Apache2 running "freely" i.e. not in container 

I have copied apache site configuration files, index.html and xxx.conf from virtualbox environment, where webchat is working
I can't find any error messages, only this comes to chatbot website http://xxx.xxxfi:444/

// you can add a version tag if you need, e.g for version 0.11.5 https://cdn.jsdelivr.net/npm/rasa-webchat@0.11.5/lib/index.min.js

Can it be user rights?

**Comment by Fugit185** [comment]
Some information below 

 

paulii@vetbot:~/rasaProd/rasaAsPa$ sudo netstat -plnt

Active Internet connections (only servers) 

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name 

tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      839/systemd-resolve 

tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1073/sshd 

tcp        0      0 127.0.0.1:29130         0.0.0.0:*               LISTEN      1423/mdsd 

tcp6       0      0 :::22                   :::*                    LISTEN      1073/sshd 

tcp6       0      0 :::444                  :::*                    LISTEN      17464/apache2 

tcp6       0      0 :::5005                 :::*                    LISTEN      72983/docker-proxy 

 

paulii@vetbot:~/rasaProd/rasaAsPa$ 

 

**index.html** 

 

paulii@vetbot:~/rasaProd/rasaAsPa$ cat index.html

 

<head>

</head>

<body>

 

<div id="webchat"></div> 

<script src="https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.min.js"></script> 

// you can add a version tag if you need, e.g for version 0.11.5 https://cdn.jsdelivr.net/npm/rasa-webchat@0.11.5/lib/index.min.js 

<script> 

  WebChat.default.init({

    selector: "#webchat",

    initPayload: "/aloitus",

    customData: {"language": "en"}, // arbitrary custom data. Stay minimal as this will be added to the socket

    socketUrl: "http://localhost:5005",

    socketPath: "/socket.io/",

    title: "Demo bot",

    subtitle: "Subtitle",

    params: {"storage": "session"} // can be set to "local"  or "session". details in storage section.

  })

</script>

</body>

</html>

 

 

**sites-availale conf** 

 

paulii@vetbot:/etc/apache2/sites-available$ cat 000-default.conf 

<VirtualHost *:444>

ServerAdmin webmaster@localhost

 

ServerName aspabotti1.omnia.fi

        ServerAlias www.aspabotti1.omnia.fi

        # DocumentRoot /home/linttu/rasaProd/rasaAsPa

        DocumentRoot /var/www/html

 

        <Directory /var/www/html>

           Options Indexes FollowSymLinks

           AllowOverride None

           Require all granted

        </Directory>

 

        ErrorLog ${APACHE_LOG_DIR}/error.log

        CustomLog ${APACHE_LOG_DIR}/access.log combined

 

</VirtualHost>

 

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

 

**Rasa docker running** 

 

paulii@vetbot:/etc/apache2/sites-available$ docker ps -a 

CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS               NAMES 

133db8a49155        rasa/rasa:1.10.11-full   "rasa run -m models …"   2 minutes ago       Up 2 minutes                0.0.0.0:5005->5005/tcp   rasa2 

 

 

**Ubuntu environment** 

paulii@vetbot:/etc/apache2/sites-available$ lsb_release -a 

No LSB modules are available. 

Distributor ID: Ubuntu 

Description:    Ubuntu 18.04.5 LTS 

Release:        18.04 

Codename:       bionic 

 

**Docker version** 

paulii@vetbot:/etc/apache2/sites-available$ docker -v 

Docker version 19.03.13, build 4484c46d9d 

 

**Apache2 version** 

paulii@vetbot:/etc/apache2/sites-available$ apache2 -v

Server version: Apache/2.4.29 (Ubuntu)

Server built:   2020-08-12T21:33:25

**Comment by Fugit185** [comment]
Could it be that javascipt needs browser to be installed to system? Because it works in my virtual box environment where I run Ubuntu 18.04 **Desktop** and in Azure it is only Ubuntu 18.04 server, no desktop, no browse?

**Comment by sumit2498** [comment]
Hi I am trying same..
i want to deploy rasa on azure. but dont know the correct procedure
will you help me?

**Comment by InnoOmnia** [comment]
> Hi I am trying same..
> i want to deploy rasa on azure. but dont know the correct procedure
> will you help me?

Sure, I use docker and apache2, follow their instructions how install them
Then, create first desired rasa folder and then move there
this is command to init rasa, check that you are user 1000, if not then change user in command
docker run -it --rm --user 1000 -v $(pwd)/:/app rasa/rasa:1.10.11-full init --no-prompt

This is to train
docker run -it --rm --user 1000 -v $(pwd):/app rasa/rasa:1.10.11-full train

This to start
docker run -it --rm --user 1002 -v $(pwd):/app rasa/rasa:1.10.11-full train

Follow webchat instructions for index.html and credentials.yml files

This is useful command to see if apache2 and rasa are running and on what ports
sudo netstat -plnt


Use these to stop and remove unneeded containers
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

Hope this helps, ask anything if needed

**Comment by InnoOmnia** [comment]
I tested with below javascript and it works, so it seems that webchat widget javascript doesn't start at all?

<html>
<head>
<script language="JavaScript">

</script>
</head>
<body>
<FORM>
<h2>Fahrenheit to Celsius Converter</h2>
Enter a temperature in degrees F: 
<INPUT NAME="DegF" VALUE="0" MAXLENGTH="15" SIZE=15>
<p>
Click this button to calculate the temperature 
in degrees C:
<INPUT NAME="calc" VALUE="Calculate" TYPE=BUTTON 
onClick=temp(this.form)>
<p>
Temperature in degrees C is: 
<INPUT NAME="DegC" READONLY SIZE=15>
</FORM>
</body>
</html>

**Comment by InnoOmnia** [comment]
<html>
<head>
<script language="JavaScript">

</script>
</head>
<body>
<FORM>
<h2>Fahrenheit to Celsius Converter</h2>
Enter a temperature in degrees F: 
<INPUT NAME="DegF" VALUE="0" MAXLENGTH="15" SIZE=15>
<p>
Click this button to calculate the temperature 
in degrees C:
<INPUT NAME="calc" VALUE="Calculate" TYPE=BUTTON 
onClick=temp(this.form)>
<p>
Temperature in degrees C is: 
<INPUT NAME="DegC" READONLY SIZE=15>
</FORM>
</body>
</html>

**Comment by InnoOmnia** [comment]
~~~
<html>
<head>
<script language="JavaScript">
<!-- hide this script from old browsers
function temp(form)
{
  var f = parseFloat(form.DegF.value, 10);
  var c = 0;
  c = (f - 32.0) * 5.0 / 9.0;
  form.DegC.value = c;
}
// done hiding from old browsers -->
</script>
</head>
<body>
<FORM>
<h2>Fahrenheit to Celsius Converter</h2>
Enter a temperature in degrees F: 
<INPUT NAME="DegF" VALUE="0" MAXLENGTH="15" SIZE=15>
<p>
Click this button to calculate the temperature 
in degrees C:
<INPUT NAME="calc" VALUE="Calculate" TYPE=BUTTON 
onClick=temp(this.form)>
<p>
Temperature in degrees C is: 
<INPUT NAME="DegC" READONLY SIZE=15>
</FORM>
</body>
</html>
~~~

**Comment by sumit2498** [comment]
> > Hi I am trying same..
> > i want to deploy rasa on azure. but dont know the correct procedure
> > will you help me?
> 
> Sure, I use docker and apache2, follow their instructions how install them
> Then, create first desired rasa folder and then move there
> this is command to init rasa, check that you are user 1000, if not then change user in command
> docker run -it --rm --user 1000 -v $(pwd)/:/app rasa/rasa:1.10.11-full init --no-prompt
> 
> This is to train
> docker run -it --rm --user 1000 -v $(pwd):/app rasa/rasa:1.10.11-full train
> 
> This to start
> docker run -it --rm --user 1002 -v $(pwd):/app rasa/rasa:1.10.11-full train
> 
> Follow webchat instructions for index.html and credentials.yml files
> 
> This is useful command to see if apache2 and rasa are running and on what ports
> sudo netstat -plnt
> 
> Use these to stop and remove unneeded containers
> docker stop $(docker ps -a -q)
> docker rm $(docker ps -a -q)
> 
> Hope this helps, ask anything if needed

Many thanks! I was struggling for the way to deploy. 
I have some qns
How did you wrote a dockerfile?
But i made a web app in flask and from that i was using the bot!(on localhost)
For what did you use apache.?
You didnt created a App Service in azure?
How many docker containers you created need?

**Comment by InnoOmnia** [comment]
Many thanks! I was struggling for the way to deploy.
I have some qns
How did you wrote a dockerfile?
>I don't use docker-compose, yet so no docker file, just those direct commands
But i made a web app in flask and from that i was using the bot!(on localhost)
>ok, is working? if so, can you share your code and configurations?
For what did you use apache.?
>I don't know, maybe I have seen many web servers using that, it is like de facto
You didnt created a App Service in azure?
>What you mean? What app service?
How many docker containers you created need"
>I have 5 chatbots so 5 dockers, they use different port (5005, 5006 etc)

Sorry wrong command here
This to start
docker run -it --rm --user 1002 -v $(pwd):/app rasa/rasa:1.10.11-full train
it should be this, see the port there
docker run --name=rasa1 --user 1002 -v $(pwd):/app -p "5005:5005" rasa/rasa:1.10.11-full run -m models --enable-api --cors "*" --debug

**Comment by InnoOmnia** [comment]
I got it working, the key was ask to IT server team to open ports at server side, this can be closed now!
