### ISSUE TITLE
Responsiveness of the bot ui

### ISSUE THREAD

**Issue by kiranbeethoju** [botfront/rasa-webchat#294]
It is not being resized based on the device when I tried to open it in a mobile view unable to fit it to that mobile screen size.
![Screenshot from 2020-09-24 19-21-07](https://user-images.githubusercontent.com/33856173/94300888-43b7ac80-ff87-11ea-84bc-a0d53f598cfa.png)

**Comment by MatthieuJnon** [comment]
Hi there seems to be an issue with your screenshot

**Comment by kiranbeethoju** [comment]
I uploaded the proper screenshot here

**Comment by kiranbeethoju** [comment]
Forgot to add viewport in html, now its working as expected..
