### ISSUE TITLE
[New parameter] Legal Disclaimer to Widget

### ISSUE THREAD

**Issue by wladneto** [botfront/rasa-webchat#297]
It would be great if there was a parameter for a chatbot disclaimer like this example:
![image](https://user-images.githubusercontent.com/15970264/95382727-7a16f500-08c0-11eb-8765-08a94afc6524.png)

**Comment by znat** [comment]
Hi, thanks for the suggestion. You can always submit a PR, or simply start your conversation with a disclaimer message

**Comment by wladneto** [comment]
Thanks @znat
