### ISSUE TITLE
Bug in displaying sequential utterances each containing buttons

### ISSUE THREAD

**Issue by Akhil-YS** [botfront/rasa-webchat#308]
For an intent (user says "hi"), I have two utterance statements which would be displayed one after the other in the UI.

If both of these utterances have buttons, then the buttons associated with the first statement are disappearing once the 2nd statement and its buttons are displayed. But, ideally, they should be persisted in the UI along with the first statement.

![web_chat_bug](https://user-images.githubusercontent.com/67151916/99068699-03fa6200-25d3-11eb-9511-e1d7526ba00e.gif)

**Comment by MatthieuJnon** [comment]
Hi, rasa webchat support two types of payloads for buttons, either your buttons are under a key name `quick_replies`, in this case, the buttons will only be showed in the latest received message.
But if you put your buttons under a `buttons` key, the buttons will always be showed (which is what you're trying to achieve)
