### ISSUE TITLE
how to send attachment file like image, video, doc, etc...

### ISSUE THREAD

**Issue by xkungfu** [botfront/rasa-webchat#309]
how to send a file from user to rasa server, not from rasa to user.

that is, on rasa-webchat Widget ui near submit button, there should be an icon of "send attachment", and after clicked, the user can send a local file to server.

**Comment by MatthieuJnon** [comment]
Hi, rasa webchat doesn't support uploading files as of now, if this is a feature that you want to add, we're open to reviewing pull requests.
