### ISSUE TITLE
how to add a button near send message button

### ISSUE THREAD

**Issue by xkungfu** [botfront/rasa-webchat#310]
hi,
I want to send image throw rasa-webchat to rasa server. but there isn't send local file feature.
so I want to add a button near send message button, after click this button, popup a box to sending local image file.
how to add a custom button?

**Comment by MatthieuJnon** [comment]
Hi, rasa webchat doesn't support uploading files as of now, if this is a feature that you want to add, we're open to reviewing pull requests.

**Comment by xkungfu** [comment]
really?I have seen issue about this years ago.
so I didn't think it is useful of a request.
My question is about a button, not upload.
thanks for reply.
