### ISSUE TITLE
Problem to connect rasa 2.0

### ISSUE THREAD

**Issue by rlence** [botfront/rasa-webchat#311]
I place in socketUrl the url indicated by rasa 2.0 http: // localhost: 5005 / webhooks / rest / webhook, although, it says in cosola that it is connected, it remains as if waiting for the server even though it is active and the connection appears on the server rasa
![Captura de pantalla 2020-11-17 a las 10 50 43](https://user-images.githubusercontent.com/40366311/99374644-15898580-28c3-11eb-8862-19e74e943d93.png)

**Comment by pheel** [comment]
Rasa-webchat is a [websocket-based channel](https://rasa.com/docs/rasa/connectors/your-own-website/#websocket-channel). It doesn't support REST.

**Comment by sid321axn** [comment]
I am also unable to connect rasa 2.0 through rasa webchat

**Comment by sid321axn** [comment]
In my case problem is now resolved

**Comment by rahabwairimu05** [comment]
@sid321axn how did you solve it? I am having challenges connecting to the webchat with Rasa 2.0, but the webchat is working perfectly well with Rasa1.0
