### ISSUE TITLE
How can I clear content or restart a conversation on widget ?

### ISSUE THREAD

**Issue by luc-tuyishime** [botfront/rasa-webchat#314]
function CustomWidget = () => {
  return (
    <Widget
      initPayload={"/get_started"}
      socketUrl={"http://localhost:5500"}
      socketPath={"/socket.io/"}
      customData={{"language": "en"}} 
      title={"Title"}
    />
  )
}

**Comment by Duciwuci** [comment]
Setting the params

```
params={{
        storage: "session",
      }}
```

will delete your storage after closing your app or Tab (not on refresh). 😄

**Comment by MatthieuJnon** [comment]
You can also manually clear the local storage on mount and on unmount to make sure that the state is always pristine. `localStorage.chat_session = null`

**Comment by LearnCodeZone** [comment]
i have faced same issue but i have fix this using this command localStorage.clear(); check full integration here:
https://youtu.be/N_A7e16L6oc
