### ISSUE TITLE
Send Image to RasaBot

### ISSUE THREAD

**Issue by Duciwuci** [botfront/rasa-webchat#319]
Is it possible to send images to the Rasa Bot?

**Comment by Fugit185** [comment]
Do you mean as response (utter)?  
Then it is like this.  
just add "-" before text as normal case, when I pasted it here it changed that to dot so I have to remove it

  >utter_cheer_up:
  >text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"
