### ISSUE TITLE
How to use profileAvatar?

### ISSUE THREAD

**Issue by Fugit185** [botfront/rasa-webchat#321]
I have understood that with "profileAvatar =" you can set up icon for bot, like robot
But how to do it?

**Comment by Fugit185** [comment]
Found this and got it working, only question, can it be local (disk) link too?

>profileAvatar: "https://rasa.com/assets/img/demo/rasa_avatar.png",

**Comment by Fugit185** [comment]
now I got it workingi with local picture, just add  

>profileAvatar: "picture.png"  

when picture is in same folder as index.hmtl. if not add path before.  

Only thing what is **still open** is how to add avatar to human "bubble" too???

**Comment by TarunUpadhyaya** [comment]
Are you referring the open Launcher Image? 

If yes then you should add
 
openLauncherImage: "image"
