### ISSUE TITLE
How to add emojis in bot responses?

### ISSUE THREAD

**Issue by sid321axn** [botfront/rasa-webchat#328]
Hi how can we add emojis in bot responses to make the bot response more expressive

**Comment by stevenbal** [comment]
It's possible using unicode https://github.com/botfront/rasa-webchat/issues/161.

It would be nice however if emojis using markdown syntax were supported (https://gist.github.com/rxaviers/7360908)

**Comment by MatthieuJnon** [comment]
Hi, thank you @stevenbal, you can indeed use unicode as stated in #161, however we are not planning to add markdown syntax for that, if you have a good solution for this, you're welcome to contribute with a PR.
