### ISSUE TITLE
Typing dots animation

### ISSUE THREAD

**Issue by tomimartin01** [botfront/rasa-webchat#337]
I would like to know if it is possible to show the animation of the typing dots just after the user send a message. Sometimes the bot takes some time to respond and it seems broken. I would like to implement some animation in this time or extend the time of the typing dots in the webchat.  
It would be a great solution that the whole time the bot is 'thinking',  the typing dots are shown on the chat to indicate the user that the bot is alive.
I tried the customMessageDelay but this was not what I was looking for, because the delay depends only of the message's lenght, I would like another solution. I am using the webchat in a script tag.

Thanks.

**Comment by liefra** [comment]
I'm also interested in this. @tomimartin01: Did you find a solution?

**Comment by amthe** [comment]
Isnt this topic beginning to get even hotter with GPT. Does anyone have a solution. People stop using my bot because they think its broken when there is no indication that a message is coming.
