### ISSUE TITLE
Webchat not working after 1.0.0 Release

### ISSUE THREAD

**Issue by TristanStettin** [botfront/rasa-webchat#339]
After the Release of Version 1.0.0 today, I've changed the script the way you can find on https://github.com/botfront/rasa-webchat in the documentation. Since that the Chatwindow is not displayed and I got an error in my console:

Uncaught TypeError: Cannot read property 'default' of undefined
    at HTMLScriptElement.e.onload

Its about the " window.Webchat.default" line of Code.

Hope you can fix this/ or tell me, how to fix it.

Best Regards

Edit: Before that, Version 0.11.12 worked fine.

**Comment by MatthieuJnon** [comment]
Thank you, it's WebChat and not Webchat 😭 Releasing 1.0.1, will let you know when it's out

**Comment by TristanStettin** [comment]
Thanks for the fast reply! Yeah ok... sorry my bad, could have seen it myself :D

**Comment by MatthieuJnon** [comment]
No worries, it's my fault really
