### ISSUE TITLE
widget not showing

### ISSUE THREAD

**Issue by vinay650** [botfront/rasa-webchat#340]
i was using it before till january 2021
, it was working fine but now even widget in my website is not visible,is there any new changes i have to make, please reply.

**Comment by MatthieuJnon** [comment]
Hi, if you're using the webchat by pasting the script in your html, you have to update to the new script in the README.
if you don't want breaking changed affecting your webchat, you have to specify a version (see the README section about that, just below the snippet)

**Comment by morganmattr** [comment]
Hey @vinay650 I ran into the same issue today and it was working for some time before that fine. It looks like the <script> code changed yesterday. Once I added in the new code per the readme, it is working: 

<script>!(function () {
  let e = document.createElement("script"),
    t = document.head || document.getElementsByTagName("head")[0];
  (e.src =
    "https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.js"),
    (e.async = !0),
    (e.onload = () => {
      window.WebChat.default(
        {
          customData: { language: "en" },
          socketUrl: "https://bf-botfront.development.agents.botfront.cloud",
          // add other props here
        },
        null
      );
    }),
    t.insertBefore(e, t.firstChild);
})();
</script>

**Comment by MatthieuJnon** [comment]
I opened a PR to make this clearer to new users

**Comment by morganmattr** [comment]
@MatthieuJnon thank you

**Comment by vinay650** [comment]
thankyou so much
