### ISSUE TITLE
After script update css doesnt work anymore

### ISSUE THREAD

**Issue by Fugit185** [botfront/rasa-webchat#342]
After script update css doesnt work anymore?

This was my previous index.html  

```
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.min.js"></script>  
    <link rel="stylesheet" type="text/css" href="st.css">
</head>
<body>
<div id="webchat"></div>
<script>
  WebChat.default.init({
    selector: "#webchat",
    initPayload: "/aloita",
    customData: {"language": "fi"}, // arbitrary custom data. Stay minimal as this will be added to the socket
    socketUrl: "http://ittukibot.omnia.fi:5012",
    socketPath: "/socket.io/",
    embedded: false,
    title: "IT tukibot",
    subtitle: "Opiskelijan IT tuki",
    inputTextFieldHint: "Kirjoita kysymys tähän...",
    profileAvatar: "robot_icon.png",
    params: {"storage": "session"} // can be set to "local"  or "session". details in storage section.
  })
</script>
</body>
</html>
```  

Then bot suddenly stopped to work, and after debugging I noticed that there is new script available and then I started to us this  

```
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="st.css">
</head>
<body>

<script>!(function () {
  let e = document.createElement("script"),
    t = document.head || document.getElementsByTagName("head")[0];
  (e.src =
    "https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.js"),
    (e.async = !0),
    (e.onload = () => {
      window.WebChat.default(
        {
          customData: { language: "en" },
          socketUrl: "http://ittukibot.omnia.fi:5012",
          embedded: false,
          title: "IT tukibot",
          subtitle: "Opiskelijan IT tuki",
          inputTextFieldHint: "Kirjoita kysymys tähän...",
          profileAvatar: "robot_icon.png",
          params: {"storage": "session"} // can be set to "local"  or "session". details in storage section.
          // add other props here
        },
        null
      );
    }),
    t.insertBefore(e, t.firstChild);
})();
</script>
</body>
</html>
```
  
Now the chatbot works again but colors are back to default, so it looks that after update the new script don't use css anymore?
Here is my st.css  
  
```
:root {
  --color: #FDBC00;
  --white: #ffffff;
}



.rw-conversation-container .rw-header {
    background-color: var(--color);
}
.rw-conversation-container .rw-client {
    background-color: var(--color);
}

.rw-conversation-container .rw-close-button {
    background-color: var(--color);
}


.rw-conversation-container .rw-reply {
    background-color: var(--color);
}


.rw-launcher{
    background-color: var(--color);
}


.rw-conversation-container .rw-replies {
display:block
}
```

So what should I try next?  
Also how to get noticed next time when script changes beforehand, not after bot is broken?

**Comment by MatthieuJnon** [comment]
Hi, I'm investigating the css issue.

> Also how to get noticed next time when script changes beforehand, not after bot is broken?

As stated in the documentation, you should fix your version so that you're not affected by major versions and breaking changes. like so https://cdn.jsdelivr.net/npm/rasa-webchat@1.0.0/lib/index.js

**Comment by Fugit185** [comment]
Yes, I noticed this  
> as stated in the documentation, you should fix your version so that you're not affected by major versions and breaking changes. like so https://cdn.jsdelivr.net/npm/rasa-webchat@1.0.0/lib/index.js  

but are scripts also versioned then?  
And what is the latest version? In versions I can see that highest is v2.14, but the strange is that is not latest updated but for example v1.0.0. I'm puzzled?

**Comment by MatthieuJnon** [comment]
The script would work with a given version, the one you had worked with all versions pre 1.0, the new one works with 1.0.
If your version doesn't change, the script doesn't have to change either.

You can see the releases here https://github.com/botfront/rasa-webchat/releases, and also here https://www.npmjs.com/package/rasa-webchat, in the versions tab. We restarted at 0.1.1 in April 2018, nearly 3 years ago. We started publishing on npm with 0.6.0 more than a year ago.

Let me know if you have any more questions

**Comment by Fugit185** [comment]
Ok, now versions are clear, only question there, what is v**1.5.0** jul 9 2020? after that again 0.11.6 etc.

**Comment by MatthieuJnon** [comment]
Probably a mistake, I removed it
