### ISSUE TITLE
Change between releases

### ISSUE THREAD

**Issue by Fugit185** [botfront/rasa-webchat#343]
Now when more and more people are using Rasa as botengine/backend and then also more and more people start using Webchat as chat frontend, should the documentation be improved too? First I looked version to to see changelog, but could not find it, then I compared versions directly and could see the changes there, but not reason, why there was change? For example why script was changed in version 1.0.0? Previous was very easy to understand, the new more cryptic? Could I help you on this documenation/changelog matter?

**Comment by MatthieuJnon** [comment]
Hi, the changes will make more sense once we release the new version of Botfront, we're working on documenting all those new features at the moment. It's true though that the changelogs could be improved
