### ISSUE TITLE
 The client is using an unsupported version of the Socket.IO or Engine.IO

### ISSUE THREAD

**Issue by gdet** [botfront/rasa-webchat#352]
Hello,

I am trying to connect your webchat with my rasa chatbot.
I have installed the latest version of rasa and when I am trying to access it from the webpage the page is blank and in the server side I can see this error: 

         The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)

Both the page and the rasa endpoint are on the same server. And I am calling rasa with this command:

        rasa run -m models --enable-api --cors "*" --debug
Also in the webpage I have this error 

     Error: xhr poll error. 
What should I do?

Thank you

**Comment by Icesource** [comment]
I also had this problem. So did you build your own source code instead of using CDN or NPM directly?

**Comment by Icesource** [comment]
Okay, author has solved this problem on Apr 16. This is just because the sock.io version is incompatible.

**Comment by gdet** [comment]
Okay thank you! So we just download the latest code?

**Comment by Icesource** [comment]
> Okay thank you! So we just download the latest code?

Yes. Keep the code and rasa latest and everything is gonna be ok.

**Comment by ttamg** [comment]
For anyone finding this now.  I found that the CDN version 1.01 was working fine now with socket.io and Rasa.

`"https://cdn.jsdelivr.net/npm/rasa-webchat@1.0.1/lib/index.js"`
