### ISSUE TITLE
Show html text?

### ISSUE THREAD

**Issue by tide90** [botfront/rasa-webchat#356]
Hey,

is it possible that the rasa-webchat can format properly text like like on a html website with tags like:

`<p>Hallo ich bin hier</p>, <p><strong>und ich bin fett</strong></p>`

or links with

` <a href="*url*">*link text* </a>`

Also with list like ul/li...

Is this possible?

**Comment by akenayou** [comment]
Hey @tide90,
Check out this repository: https://github.com/JiteshGaikwad/ChatbotWidget/blob/main/README.md
I believe you will find what you're looking for
