### ISSUE TITLE
Open url from quick reply/button in current tab

### ISSUE THREAD

**Issue by humcasma** [botfront/rasa-webchat#364]
I have a carousel with buttons of type `web_url`. When I click on the buttons, a new browser tab is opened. I would like the url to be opened in the current tab (i.e., in the tab/window that hosts the webchat widget). How can this be done?

**Comment by liefra** [comment]
Have a look at the [Advanced response configuration](https://botfront.io/docs/rasa/response-types/#advanced-response-configuration). These allow to decide where links should open

**Comment by humcasma** [comment]
Thanks @liefra 
I had not seen all those options. Really nice!
What if I want to generate the response from code? I tried doing it as shown below, but it did not work.

`class CustomAction(Action):

    async def run(self, dispatcher, tracker: Tracker, domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
       carousel = {
            "type": "template",
            "payload": {
                "template_type": "generic",
                "elements": [
                  {
                        "title": "Title1",
                        "buttons": [{
                            "title": "Item1",
                            "url": "https://.....",
                            "type": "web_url"
                            }
                        ]
                  },
                  {
                        "title": "Item 2",
                        ....
                  },
                ],
                "metadata": {
                    "linkTarget": "_self",
                }
            }
        }
        dispatcher.utter_message(attachment=carousel)        
        return []
`

**Comment by Johan1us** [comment]
I would also like to know this
