### ISSUE TITLE
interacting with webchat from within webpage

### ISSUE THREAD

**Issue by mmenti** [botfront/rasa-webchat#37]
Hi all  - this is a question rather than an issue/problem as such, hope it's ok to bring it up here.

I have a client requirement where I need to trigger an action/message from the webpage that the Rasa webchat widget is embedded on. E.g. someone clicks on a link on the web page, and a custom action or message appears in the webchat widget that's embedded on that page.

I was vaguely thinking maybe making a POST request to the Rasa action server, duplicating what Rasa Core sends to it, but I'm not sure how to match things like sender ids etc to make that work (if it's even possible).

I realise this may be outside the scope of this, so feel free to close it so, I was just wondering in case anyone here had done something similar before.

**Comment by znat** [comment]
That's an interesting idea. One way would be to expose a new function
WebChat.sendMessage(msg) in the same way open, close, show and hide are
exposed.
If you're willing to do it we'll gladly accept a PR.

Le lun. 10 déc. 2018 10 h 31, Mario Menti <notifications@github.com> a
écrit :

**Comment by mmenti** [comment]
@znat thanks, I'll take a look! Sadly not super familiar with React, but may be able to gather enough from looking through source :)

**Comment by mmenti** [comment]
@znat I think I have something working, for sending simple text messages (which is all my particular user case requires right now). But.. I'm struggling to figure out how to implement any tests (I can't actually even get the existing ones to run successfully), but the project builds, and it works at least as an embedded <script> in a test page (a temporary test page is at http://35.178.228.52/rasa-webchat). Is that sufficient to submit a PR, or would you want me to add tests also?

**Comment by MatthieuJnon** [comment]
For anyone looking through this issue, the webchat react component now exposes a `sendMessage(payload: string, text?: string)` function through its ref. You can then call this method whenever you want from your front end.

**Comment by xkungfu** [comment]
> @znat I think I have something working, for sending simple text messages (which is all my particular use case requires right now). But.. I'm struggling to figure out how to implement any tests (I can't actually even get the existing ones to run successfully), but the project builds, and it works at least as an embedded <script> in a test page (a temporary test page is at http://35.178.228.52/rasa-webchat). Is that sufficient to submit a PR, or would you want me to add tests also?


Got error of your example code:
```
Uncaught TypeError: WebChat.sendMessage is not a function
    at sendMessageToWidget (test-rasawebchat:56)
    at HTMLAnchorElement.onclick

```
Please help: How to define the function "WebChat.sendMessage"?

thanks!

**Comment by xkungfu** [comment]
> For anyone looking through this issue, the webchat react component now exposes a `sendMessage(payload: string, text?: string)` function through its ref. You can then call this method whenever you want from your front end.

dose it must send a message to rasa first? and then put the response to chatbox window?
can I directly put some text or element to the window?
