### ISSUE TITLE
Demo code at https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.js - need updating?

### ISSUE THREAD

**Issue by pomegran** [botfront/rasa-webchat#370]
Hi,

I am using your demo code at the above URL which seems to have stopped working.  I noticed there have been some socket.io changes in the last 12 hours - does the above need updating too?

Many thanks!

**Comment by MatthieuJnon** [comment]
Hi, I added some extra clarification in the readme, check it out https://github.com/botfront/rasa-webchat/pull/374

**Comment by pomegran** [comment]
I tried this with my RASA 2.2.8 install pointing to version 1.0.0 - worked as expected, thank you!

However, my RASA 2.4.3 does not work with the latest version or explicitly calling 1.0.1.  It's not urgent, but wanted to make you aware.

This is what I see in Chrome Developer view.

![image](https://user-images.githubusercontent.com/13970301/115304901-6dbc0080-a15d-11eb-929d-0cbe7955c043.png)
