### ISSUE TITLE
pressings enter doesn't work in rasa-webchat widget

### ISSUE THREAD

**Issue by kapilkathuria** [botfront/rasa-webchat#375]
Hi,

I am trying to setup "hello world" for rasa-webchat with react. 

all seems to work fine except pressing enter in widget doesn't send the message. clicking with mouse on send icon works fine.

am i missing anything?

below is list of packages installed.
```
  "dependencies": {
    "rasa-webchat": "^1.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3"
  },
```
node version
`v12.22.1`

![image](https://user-images.githubusercontent.com/24175636/115942106-29ff2900-a4c6-11eb-9462-b900c9216198.png)

**Comment by MarcelWepper** [comment]
Same issue for me - on an oder Version, it was working. Maybe an onClick event with an trigger will do the trick.

**Comment by HUYIJUNCODING** [comment]
> Hi,
> 
> I am trying to setup "hello world" for rasa-webchat with react.
> 
> all seems to work fine except pressing enter in widget doesn't send the message. clicking with mouse on send icon works fine.
> 
> am i missing anything?
> 
> below is list of packages installed.
> 
> ```
>   "dependencies": {
>     "rasa-webchat": "^1.0.1",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "react-scripts": "4.0.3"
>   },
> ```
> 
> node version
> `v12.22.1`
> 
> ![image](https://user-images.githubusercontent.com/24175636/115942106-29ff2900-a4c6-11eb-9462-b900c9216198.png)

Why can't I install the same dependencies, but the interface doesn't come out

**Comment by MarcelWepper** [comment]
@HUYIJUNCODING there is the 
"hideWhenNotConnected | true | If true the widget will hide when the connection to the socket is lost" property. When there is no socket to connect to, your bot will not be displayed.
