### ISSUE TITLE
Widget as a React Component not working properly

### ISSUE THREAD

**Issue by guilosost** [botfront/rasa-webchat#378]
I integrated the Widget as a React Component and it doesn't work completely fine. I am using rasa-webchat@1.0.0 version.

The chat icon inside the widget bubble is smaller than the one that appears when you use the script and the "popup messages" that shows up are in blank whereas with the script it works perfectly.

This is my code:

```
import Widget from 'rasa-webchat';

function CustomWidget() {
  return (
    <Widget
      initPayload={"/get_started"}
      socketUrl="http://localhost:5005"
      socketPath={"/socket.io/"}
      customData={{"language": "es"}} // arbitrary custom data. Stay minimal as this will be added to the socket
      title={"Bienvenido"}  
    />
  )
}

export default CustomWidget;
```

And this is the problem itself: 
![Selección_002](https://user-images.githubusercontent.com/48485791/116520486-15aa9a00-a8d3-11eb-8625-d26f6701f6ee.png)

I also got this error in the console log, but I don't know what it refers to as the problem comes from the minified js:
![Selección_003](https://user-images.githubusercontent.com/48485791/116521101-d6307d80-a8d3-11eb-90ad-f1d5784e9337.png)

**Comment by HUYIJUNCODING** [comment]
> I integrated the Widget as a React Component and it doesn't work completely fine. I am using rasa-webchat@1.0.0 version.
> 
> The chat icon inside the widget bubble is smaller than the one that appears when you use the script and the "popup messages" that shows up are in blank whereas with the script it works perfectly.
> 
> This is my code:
> 
> ```
> import Widget from 'rasa-webchat';
> 
> function CustomWidget() {
>   return (
>     <Widget
>       initPayload={"/get_started"}
>       socketUrl="http://localhost:5005"
>       socketPath={"/socket.io/"}
>       customData={{"language": "es"}} // arbitrary custom data. Stay minimal as this will be added to the socket
>       title={"Bienvenido"}  
>     />
>   )
> }
> 
> export default CustomWidget;
> ```
> 
> And this is the problem itself:
> ![Selección_002](https://user-images.githubusercontent.com/48485791/116520486-15aa9a00-a8d3-11eb-8625-d26f6701f6ee.png)
> 
> I also got this error in the console log, but I don't know what it refers to as the problem comes from the minified js:
> ![Selección_003](https://user-images.githubusercontent.com/48485791/116521101-d6307d80-a8d3-11eb-90ad-f1d5784e9337.png)

![企业微信截图_16204430832537](https://user-images.githubusercontent.com/33798719/117523880-42566400-afed-11eb-8d5a-e37efdef7b34.png)
![企业微信截图_16204431464242](https://user-images.githubusercontent.com/33798719/117523900-60bc5f80-afed-11eb-9bf9-e69c9b93fa71.png)
