### ISSUE TITLE
React component and JS not working with Rasa

### ISSUE THREAD

**Issue by kaplan441** [botfront/rasa-webchat#379]
I integrated the Widget as a React Component and it doesn't work. And also i tried JS. Problem and exception is same.

I checked network tab in chrome and i saw request with http 200.
For example:
	ÿ0{"sid":"5de50ac9fe234630befdc06543535cb2","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}

But there is an exception in chrome console:
`Error: server error
    at u.onPacket (index.js:116)
    at e.exports.<anonymous> (index.js:116)
    at e.exports.r.emit (index.js:1)
    at e.exports.onPacket (index.js:12)
    at index.js:17
    at Array.forEach (<anonymous>)
    at e.exports.onData (index.js:17)
    at f.<anonymous> (index.js:116)
    at f.r.emit (index.js:1)
    at f.onData (index.js:116)`

I throws from case 'error' from onPacket method. input e.type=error, e.data= 'parser error'

How can i fix this problem.

Versions:
rasa-webchat: 1.0.1
Rasa: 2.3.1
Rasa-x: 0.37

Thanks.

**Comment by HUYIJUNCODING** [comment]
I also encountered the same problem

**Comment by HUYIJUNCODING** [comment]
> I integrated the Widget as a React Component and it doesn't work. And also i tried JS. Problem and exception is same.
> 
> I checked network tab in chrome and i saw request with http 200.
> For example:
> � ÿ0{"sid":"5de50ac9fe234630befdc06543535cb2","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}
> 
> But there is an exception in chrome console:
> `Error: server error at u.onPacket (index.js:116) at e.exports.<anonymous> (index.js:116) at e.exports.r.emit (index.js:1) at e.exports.onPacket (index.js:12) at index.js:17 at Array.forEach (<anonymous>) at e.exports.onData (index.js:17) at f.<anonymous> (index.js:116) at f.r.emit (index.js:1) at f.onData (index.js:116)`
> 
> I throws from case 'error' from onPacket method. input e.type=error, e.data= 'parser error'
> 
> How can i fix this problem.
> 
> Versions:
> rasa-webchat: 1.0.1
> Rasa: 2.3.1
> Rasa-x: 0.37
> 
> Thanks.

I also encountered the same problem

**Comment by HUYIJUNCODING** [comment]
> You can try downgrade to v1.0.0

v1.0.0 not runing,Can you see your dependency information

**Comment by ndcuong869** [comment]
My dependency in Reactjs project:
"@reduxjs/toolkit": "^1.5.1",
    "rasa-webchat": "^1.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "redux": "^4.1.0",
    "web-vitals": "^1.1.1"

**Comment by HUYIJUNCODING** [comment]
> My dependency in Reactjs project:
> "@reduxjs/toolkit": "^1.5.1",
> "rasa-webchat": "^1.0.0",
> "react": "^17.0.2",
> "react-dom": "^17.0.2",
> "react-router-dom": "^5.2.0",
> "react-scripts": "4.0.3",
> "redux": "^4.1.0",
> "web-vitals": "^1.1.1"

me too ,Why not mine .

**Comment by ndcuong869** [comment]
You can upload your source code to I can find the hidden problem.

**Comment by HUYIJUNCODING** [comment]
> You can upload your source code to I can find the hidden problem.

there is my source code ,thank you !
[source code ](https://github.com/HUYIJUNCODING/rasa-webchat)
