### ISSUE TITLE
Botfront widget not showing up.

### ISSUE THREAD

**Issue by Freemanlabs** [botfront/rasa-webchat#382]
I am trying to test the script on the README.md by placing it directly into an `HTML` file. However, nothing shows up. I just see a blank page. What could I be doing wrong?

Inspecting the console, I see:

```
Error: server error
    at u.onPacket (index.js:116)
    at e.exports.<anonymous> (index.js:116)
    at e.exports.r.emit (index.js:1)
    at e.exports.onPacket (index.js:12)
    at index.js:17
    at Array.forEach (<anonymous>)
    at e.exports.onData (index.js:17)
    at f.<anonymous> (index.js:116)
    at f.r.emit (index.js:1)
    at f.onData (index.js:116)
```

**Comment by oldmonkABA** [comment]
I get the same error

**Comment by oldmonkABA** [comment]
this issue has been resolved here : https://github.com/botfront/rasa-webchat/pull/374/commits/99f06b84c6303f01d7e4db309b5454b59b09655c

**Comment by SubhadipGitHub** [comment]
I tried with both face the same issue.
![image](https://user-images.githubusercontent.com/29476358/126463101-78a8560e-9d87-489c-8133-70aa15cd7620.png)
![image](https://user-images.githubusercontent.com/29476358/126463188-0e9cfcdc-b184-403e-bd41-c0ee12abc8fa.png)

**Comment by prestonzen** [comment]
I also get the same error after testing with both urls and both 1.0.0 & 1.0.1.
