### ISSUE TITLE
Bot messages not aligned

### ISSUE THREAD

**Issue by jessicaduque** [botfront/rasa-webchat#384]
This is a problem that doesn't happen when I don't use the `profileAvatar:`, but when I use it, for some reason the messages the bot sends don't align. The first one is always more to the left, while any other message said after will be aligned with one another, but all a little bit more to the right when compared to the first message. I've tried to search about where to fix it, but I really have no clue, can anyone please help?

**Comment by liefra** [comment]
I don't have a solution, but seeing the same issue. Tried to fix it with CSS tweaks, so far without success.

**Comment by jasonpraful** [comment]
Use this style code to hide the profile avatar on messages

```
.rw-message > img {
  display: block !important;
  visibility: hidden !important;
  width: 0px !important;
  margin: 0px !important;
  border: 0px !important;
  padding: 0px !important;
}

.rw-with-avatar {
  margin-left: 5px !important;
}

.rw-response{
  margin-left: 5px !important;
}
```

Will add the portion to fix the styling with the avatar in another comment :) Hope this helps

**Comment by liefra** [comment]
@jasonpraful : Thank you for following up on this. This is indeed helpful. Would be great to see a CSS snippet for a solution with the agent. I tried it, but could make it work.

**Comment by jasonpraful** [comment]
> @jasonpraful : Thank you for following up on this. This is indeed helpful. Would be great to see a CSS snippet for a solution with the agent. I tried it, but could make it work.

Are you using classic JavaScript or a front-end framework like react?

**Comment by bharat-mauvetix** [comment]
> Use this style code to hide the profile avatar on messages
> 
> ```
> .rw-message > img {
>   display: block !important;
>   visibility: hidden !important;
>   width: 0px !important;
>   margin: 0px !important;
>   border: 0px !important;
>   padding: 0px !important;
> }
> 
> .rw-with-avatar {
>   margin-left: 5px !important;
> }
> 
> .rw-response{
>   margin-left: 5px !important;
> }
> ```
> 
> Will add the portion to fix the styling with the avatar in another comment :) Hope this helps

Hi, were you able to find a solution for text alignment with profileavatar?

**Comment by liefra** [comment]
> Are you using classic JavaScript



> > @jasonpraful : Thank you for following up on this. This is indeed helpful. Would be great to see a CSS snippet for a solution with the agent. I tried it, but could make it work.
> 
> Are you using classic JavaScript or a front-end framework like react? @liefra

Sorry, I completely missed your reply. I'm using classic Javascript, not react.

**Comment by liefra** [comment]
> > Use this style code to hide the profile avatar on messages
> > ```
> > .rw-message > img {
> >   display: block !important;
> >   visibility: hidden !important;
> >   width: 0px !important;
> >   margin: 0px !important;
> >   border: 0px !important;
> >   padding: 0px !important;
> > }
> > 
> > .rw-with-avatar {
> >   margin-left: 5px !important;
> > }
> > 
> > .rw-response{
> >   margin-left: 5px !important;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will add the portion to fix the styling with the avatar in another comment :) Hope this helps
> 
> Hi, were you able to find a solution for text alignment with profileavatar?

No, I haven't see a proper solution yet for text alignment with avatar
