### ISSUE TITLE
Can we change the host address for human handoff?

### ISSUE THREAD

**Issue by neelkantnewra** [botfront/rasa-webchat#387]
Actually, I am looking for a way to have human handoff in this chatbot interface.

Assume, Currently, it is hosting on `localhost:5005`, but I want it to change to `localhost:3000` when a custom action   `action_human_handoff` is triggered. I am using socket programming. 

i want a user human handoff in this rasa-webchat

**Comment by mandarini** [comment]
Hi there, I'm trying the same thing actually. @MatthieuJnon any ideas here?

For now, I am just removing and reloading the script, passing a new URL. But this has as a result for the chat window to restart/reload, as well. Do you know if there's a way to do that without reloading the script/etc?

**Comment by mandarini** [comment]
ping

**Comment by Apatsi** [comment]
bump
