### ISSUE TITLE
Toggle chat window visibility from javascript

### ISSUE THREAD

**Issue by iwt-kschoenrock** [botfront/rasa-webchat#396]
Hi! We've upgraded our chat client to version 1.0.0, and have noticed, that methods like `toggleChat` are not available from the WebChat object anymore. It seems only `getSessionId`, `sendMessage` and `updateRules`.

Is this function still available?

**Comment by iwt-kschoenrock** [comment]
This does not seem possible from the React component either, is there a reason for it?

**Comment by dennismetz** [comment]
Any updates?
