### ISSUE TITLE
Chat widget doesn't show up when I disable with hidewhennotconnected

### ISSUE THREAD

**Issue by Horizon733** [botfront/rasa-webchat#397]
Hi, I tried to make hideWhenNotConnected to false, but it was not showing me the chat widget. Below is the screenshot for the same.
![image](https://user-images.githubusercontent.com/57827233/132125806-e7b3760a-c4a8-4bd7-ac85-fcd8cf831416.png)
![image](https://user-images.githubusercontent.com/57827233/132125875-d1fe7ffd-7675-4365-9504-e244a75a4ce7.png)

**Comment by prestonzen** [comment]
I'm having the same issue. Did you try changing the localhost to the rasa server ip address?

**Comment by Horizon733** [comment]
> I'm having the same issue. Did you try changing the localhost to the rasa server ip address?

Yes I did, then too same issue
