### ISSUE TITLE
Buttons are not persistent [help wanted]

### ISSUE THREAD

**Issue by bharat-mauvetix** [botfront/rasa-webchat#398]
In Rasa-Webchat UI, the buttons are not persistent when the user has selected an answer. 
The syntax I have used in domain.yml for buttons 
![image](https://user-images.githubusercontent.com/76276020/134146383-67d04ee5-4f69-48a7-8aa0-6ee087a7d71e.png)
Once the option is selected the buttons are disappearing.
![image](https://user-images.githubusercontent.com/76276020/134146755-350ac2ef-0c80-4cd2-bf6d-35a98c3d0f3b.png)
![image](https://user-images.githubusercontent.com/76276020/134146827-bebf2a76-ab87-4ac2-938c-09434f9f361a.png)

**Comment by liefra** [comment]
Did you see already the chapter in the [docs](https://botfront.io/docs/rasa/response-types/#buttons-and-quick-replies) about the difference between `quick_replies` and `buttons` and how to use them?

**Comment by bharat-mauvetix** [comment]
> Did you see already the chapter in the [docs](https://botfront.io/docs/rasa/response-types/#buttons-and-quick-replies) about the difference between `quick_replies` and `buttons` and how to use them?

The doc is for botfront, I am not using botfront.

**Comment by bharat-mauvetix** [comment]
> Check line
> 
> https://github.com/botfront/rasa-webchat/blob/0119e94e6df7b84c3edf1db6f3be3aee7fa3db43/src/components/Widget/components/Conversation/components/Messages/components/Buttons/index.js#L42
> 
> ,
> change to true "persist" parameter when call function , this work for me

change the value from persit to true in the 42nd line ? as there is already mentioned true in 108th line. could you please clarify?
