### ISSUE TITLE
Chatbot button not visible when using ConnectOn

### ISSUE THREAD

**Issue by fa12behrens** [botfront/rasa-webchat#399]
Hi,

we are using the "connectOn" state "open" to reduce unnecessary requests combined with "hideWhenNotConnected" state "false".

However since we use that, the chatbot widget / button is hidden by default.

<div id="root"><div class="App"><div><div class="container"><div class="" style="display: none;"><div class="rw-widget-container"> ...

Before that usage the chatbot was visible but did had to many requests, so we applied these changes.
Now the div will just stay on "display: none" (unless manually changed in dev tools).

Is this a known issue or "feature"?
How can we fix that or is there an alternative way to reduce the requests done to the chatbot, while the chat is not opened?

Thanks in advance.

**Comment by pramod1812** [comment]
@fa12behrens ,

I am facing the same issue with connectOn property. Have you found any solution?

**Comment by fa12behrens** [comment]
Hi pramod1812,

unfortunately we did not find any solution to it yet.
As the div container which is display: hidden is created in the <Widget... step, so it cannot directly be prevented, but we are searching for a work around.

The problem also seems, that at least for us the ConnectOn does really just hide the div container, as soon as it is manually changed to display: block for example, than the requests will start being made again, despite the chat window being still closed, just by the display of the chat button.

So we are thinking of adding a placeholder button, which is the same as the chatbot one but doesn't have it's logic.
When this placeholder is clicked or hovered over, then it will fade and the true chatbot button will be displayed.
This requires additional javascript action and the solution is not flawless, but we will try it and see if it is an actual workaround for that problem.

But of course a parameter which would prevent/stop requests when the chat itself is not open would be a better option.
