### ISSUE TITLE
Webchat UI not visible on the server

### ISSUE THREAD

**Issue by srichaitanyatejaswi** [botfront/rasa-webchat#402]
When webchat is ran locally, it ran successfully with localhost confirming connection and session. but when it's deployed on a server it says connected but no session confirmation. The UI is not displaying and there are no errors in the logs as well.
Can some please point me in a right direction as where to make changes in order to run the UI on a server?

PS: Would downgrading the webchat version be helpful?
Thank you

FYI
Rasa version: 2.8.1
webchat versions tried: 1.0.0 and 1.0.1

**Comment by Atharv157** [comment]
Hey @srichaitanyatejaswi !! 
I am facing this same issue, did you find any fix?
