### ISSUE TITLE
How to add user Avatar ?

### ISSUE THREAD

**Issue by naveensiwas** [botfront/rasa-webchat#412]
Can someone please help me out, how to add userAvatar ?

I understood from this (https://github.com/botfront/rasa-webchat/issues/321) about profileAvatar and openLauncherImage

Examples :

profileAvatar: "image-url",
openLauncherImage: "image-url"

**Comment by rajalala** [comment]
Do you mean an image that would represent user that is talking to the chatbot?

**Comment by shavone328** [comment]
any update on this? Or is it possible to modify the code ourselves?
