### ISSUE TITLE
How to send a JWT token from webchat?

### ISSUE THREAD

**Issue by srichaitanyatejaswi** [botfront/rasa-webchat#414]
Hi all,

I’m trying to know how to send a JWT token for authentication from botfront webchat UI. Now I know how to secure rasa API as per their docs but I’m not sure how to send a token within the payload from webchat UI or it’s code. 

If anyone can help in this as soon as possible. I would greatly appreciate it.

Rasa version: 2.8.1
Webchat version:1.0.1

**Comment by georgebrianb** [comment]
Hey, did you manage to do this? I'm trying to do something similar.
