### ISSUE TITLE
¿Can I change the parameter language that goes in customData to the widget, without recharging the page?

### ISSUE THREAD

**Issue by andrebernardezbrana** [botfront/rasa-webchat#432]
I want to be able to communicate with the bot in two languages, so changing this parameter solves it. The problem is that the page needs to be reloaded for it to be possible.
I'm using React and using a variable as a parameter with useState() doesn't work. I think because such parameter is only used for connection but not for rendering anything.

¿Any help?

**Comment by amritpal7** [comment]
How are you able to change the language, can you pls show your code where you made changes.
