### ISSUE TITLE
Notification on new incoming messages

### ISSUE THREAD

**Issue by joshuapro14** [botfront/rasa-webchat#44]
Is there a way to get notified when webchat receives any message or is there a way to get the size of messages?

**Comment by joshuapro14** [comment]
Have implemented it; would you mind to see?
https://github.com/joshuapro14/rasa-webchat

**Comment by mofortin** [comment]
The feature has now been implemented in the latest version.

You can either use the props `displayUnreadCount` or create a custom notification system in combination with the props `onSocketEvent`
