### ISSUE TITLE
Custom Button in the header

### ISSUE THREAD

**Issue by AnsumanMishra-git** [botfront/rasa-webchat#456]
I want to add a custom buttom in the header to restart the chat and clear the messages . How to achieve that?

**Comment by soerenetler** [comment]
This sounds great, I would also like this feature. I know how to add the visual pard. But would have to do more research on the part of getting a new conversation id and reconnecting the socket. Do you know how to do that?

**Comment by juanitobello** [comment]
I have the same question, I would like to add a button with a microphone to dictate the message before sending it
like: 
![imagen con micro](https://user-images.githubusercontent.com/94077888/229990777-3195bc9d-1d7d-4978-9110-22ab11c6f6ba.PNG)

**Comment by Imadbenali19** [comment]
i am using rasa and i want to add a custom button in the webchat header to clear the chatbot history, but i cannot access to the components of the project. Is there any option to add a button
Tnx
