### ISSUE TITLE
Waiting for server...

### ISSUE THREAD

**Issue by CDFO** [botfront/rasa-webchat#52]
Hi,

I'm new to rasa-webchat, and trying to get it working with an Angular project. SocketIO is running on port 5002, and I can see following GET/POST from the front-end. But no data being exchanged, and UI says "Waiting for server...". 

Can anyone please help/advise? 

"GET /socket.io/?EIO=3&transport=polling&t=MVz-uNz&sid=a02f3e5509144af494d9e02866296be7 HTTP/1.1" 200 211 25.986784
engineio.server  - a02f3e5509144af494d9e02866296be7: Received packet PING data None
engineio.server  - a02f3e5509144af494d9e02866296be7: Sending packet PONG data None
"POST /socket.io/?EIO=3&transport=polling&t=MVz_53_&sid=a02f3e5509144af494d9e02866296be7 HTTP/1.1" 200 195 0.015423

**Comment by arni5na** [comment]
This was resolved in this issue: #28
