### ISSUE TITLE
HTML table

### ISSUE THREAD

**Issue by EmannuelRoque** [botfront/rasa-webchat#60]
Folks, can I send a html table as message? It is rendering as plain text.

Thanks
Emannuel Roque

**Comment by znat** [comment]
You should be able to send a markdown table

**Comment by Diwahars** [comment]
@znat Can you show us some examples?

**Comment by EmannuelRoque** [comment]
<table><tr><td>Data do Débito: 10-03-2013</td></tr><tr><td>Produto:37-CREDITO 1 MINUTO-PRE</td></tr><tr><td>Conta:CPB PRICE PRE-CRED.1 MINUTO-GAR.PES.</td></tr><tr><td>Agencia</td></tr><tr><td> ---- </tr></td></table>

I get this table as a string in a custom action. I'm trying to convert to markdown using python3....

I still can not make it work.

How can I implement a break line inside the string / variable?

Thanks !

**Comment by michaelscof** [comment]
Any updates @EmannuelRoque on this? Did you manage to achieve this?

**Comment by EmannuelRoque** [comment]
Hi,

I imported this 
from markdownify import markdownify as md

Then I wrote this custom action:

        try:
            with urllib.request.urlopen("url that return json") as url:
                 data = json.loads(url.read().decode())
                 resultado = data['resultset']
                 dispatcher.utter_message(resultado)
                 for i, linha in enumerate(resultado):
                     dt_vcto = linha[0]
                     compl1 = linha[1]
                     ngd = linha[2]
                     ope = linha[3]
                     produto = linha[4]
                     saldo = linha[5]
                     dispatcher.utter_message(md("<strong>" + ope + "</strong><br/>-------------<br/>Vencimento: " + dt_vcto + "<br/>" + ngd + "<br/>" + produto + "<br/>" + compl1 + "<br/> Saldo: " + saldo + "<br/>"))
            return [SlotSet('tem_divida', True)]

This solution is more adequated in terms of ux. Each line works like a new post.

Thanks!
