### ISSUE TITLE
It is not loading in IE11, does it supports ES5 browsers?

### ISSUE THREAD

**Issue by aggarwalrahul86** [botfront/rasa-webchat#63]

**Comment by thienduongccc** [comment]
Is there any solution for this issue? I am also stuck with it :(

**Comment by suhasraok** [comment]
To make this work for IE, I had to add "core-js": "^3.1.3" to the "package.json" and import 
1. 'core-js/es/array/includes'
2. 'core-js/es/array/from'
3. 'core-js/es/object/values'

**Comment by thienduongccc** [comment]
Hi Suhasraok, thank for your comments. great to know that you made it work on IE. Could you please give some more details (by code or screenshots)? appreciate it.

**Comment by topcoder613** [comment]
it's not working for me

**Comment by antoniachen** [comment]
Hi,
I'm facing a similar issue where the rasa-webchat doesn't work on IE 11. is there a work around? Also did Suhasraok's suggestion work for anyone else? I was not able to get it to work.

**Comment by thakkelk** [comment]
@antoniachen  did you get it to work in IE 11?

**Comment by MatthieuJnon** [comment]
Hi, unfortunately IE11 is not part of the browsers we support.
