### ISSUE TITLE
Show Typing dots when user wait ...

### ISSUE THREAD

**Issue by eziolotta** [botfront/rasa-webchat#66]
there is a function or an exposed prop that displays 'typing dots'  while user waiting for an answer? I can not find it.  How have you solved this problem?  there is same fork of this project that  improve this gui component?
thanks...

**Comment by EmannuelRoque** [comment]
We realy need implement this to improve the ux.

Can we post a gif image that simulating some one writting and then overwrite this image with the new message?

Can we delete a message that it's already posted?

**Comment by MatthieuJnon** [comment]
This is implemented in the latest versions, the typing dots duration will also change depending on the length of the incoming message, you can also tweak that length using the `customMessageDelay` props
