### ISSUE TITLE
the UI does not connect to the server

### ISSUE THREAD

**Issue by HishamElamir** [botfront/rasa-webchat#77]
Hi everyone,

I am wondering, is there any way to check if the sockets on the server/UI receives and send the data, because when i run the server it's receive and send the just for one time and it's disconnect. And i do not know the reason behind this.

Thanks in advance for helping.

**Comment by HishamElamir** [comment]
The progress i got so far is that the server catches the sockets for the interface and the chatbot returns the answers, but there's some thing prevent the server to send these answers to the interface.

**Comment by MatthieuJnon** [comment]
Hi, I think your issue here is server side and not rasa webchat related. But please open a new issue if I'm wrong
