### ISSUE TITLE
From where do i call the localStorage.clear() to start from scratch everytime ?

### ISSUE THREAD

**Issue by Ajith-Shenoy** [botfront/rasa-webchat#81]
I'm using rasa-webchat using html script tag method. How can i make sure that every time i open the chatbot , the previous state isn't stored.
I'm using local host

**Comment by gurpreetbajwa** [comment]
You can simply add localStorage.clear() in your script tag.

**Comment by MAHTIT** [comment]
@gurpreetbajwa can you help me with this please??
