### ISSUE TITLE
How to add speech recognition in this UI?

### ISSUE THREAD

**Issue by SandraAnildas** [botfront/rasa-webchat#82]
Is it possible to modify html code?
If yes, where do I do that?
I want include speech recognition in this design
Kindly help me

**Comment by amitbend** [comment]
You can use chrome's speech recognition - but it will require some development

**Comment by mohamedHassanKa** [comment]
I would like to know if you managed to implment any solution for this

**Comment by lucaslmmanoel** [comment]
https://medium.com/space10/the-conversational-form-evolved-now-with-voice-bc4f9a7da79f
I guess that something like this could help

**Comment by jwjuven** [comment]
I have added react-speech-recognition component into sender/index.js. and I also got the transcript in return statement of render(), but I want to send the text of voice recognition to bot, I wonder how to handle it?
I had tried the following codes in my handleSpeech method:
const {message} = this.props.trascript
this.props.sendMessage(message)

But the text didn't be sent to chat bot. 

Could you give some comments on how to send voice-text to bot?

Thanks.

**Comment by amroamer** [comment]
@jwjuven use the API "WebChat.send(payload, text: optionnal) "

**Comment by MatthieuJnon** [comment]
Exactly what @amroamer said, this method is also available through the refs of the react component when used in a React application.
