### ISSUE TITLE
How can I return an image or a video through custom actions in Python?

### ISSUE THREAD

**Issue by Chatzimina** [botfront/rasa-webchat#85]
Hello everyone,
can anyone help me with returning an image or a video through custom actions in Python? I have tried with the format here but I am sure I don't do something correctly. I have managed to make payload work like this:

     buttons.append({'title': locationch,'payload': '/show_tours{"location": "'+locationch+'"}'})
     dispatcher.utter_button_message('I found multiple locations which one is correct?', buttons=buttons)

any example will be useful,
thank you

**Comment by soundaraj** [comment]
In your custom action
 `if intent == 'show_tours:`
          ` dispatcher.utter_response({'text':'your location','image':'img url'})`
