### ISSUE TITLE
Webchat doesn't load in Internet Explorer 11.

### ISSUE THREAD

**Issue by thienduongccc** [botfront/rasa-webchat#86]
Hi everyone,

does anybody success to load the chatbot on the IE 11? I have error from console say "SCRIPT438: Object doesn't support property or method 'values'". I used webchat-0.5.7.js

**Comment by serge-bykov** [comment]
+1 on this issue 
![image](https://user-images.githubusercontent.com/47681578/59504610-5335e380-8e71-11e9-975f-4b4171950039.png)

**Comment by lihe-iw** [comment]
+1 on this issue, too

I've got the same error message:
> ![image](https://user-images.githubusercontent.com/47681578/59504610-5335e380-8e71-11e9-975f-4b4171950039.png)

while using webchat-0.5.9.js.

Tried older versions and on 0.4.2 it seemed to have been working.

**Comment by vinaykumarsripuram** [comment]
Anyone succeeded on loading WebChat on Internet explorer?

**Comment by MatthieuJnon** [comment]
Hi, unfortunately, we do not support IE11

**Comment by serge-bykov** [comment]
@vinaykumarsripuram @MatthieuJnon 
We made the widget work with IE11 by adding polyfill to the missing property: Element.prototype.append
You can generate your polyfil or as needed from polyfill.io and then include the link in your code:
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes"></script>

**Comment by MatthieuJnon** [comment]
Thank you for the help @sbkv
