### ISSUE TITLE
Link Snippets: Sending multiple link/buttons

### ISSUE THREAD

**Issue by muelerma** [botfront/rasa-webchat#87]
Hello everybody,

I played around with this but could not get it to work. Basically I just want that when sending a snippet message, there are multiple links shown below the title.

I tried two different variations here, first expanding the "buttons" list, secondly expanding the elements list, but still only one link is shown (like in the gif in the readme):
1st try:
```message = {
  "attachment":{
    "type":"template",
    "payload":{
      "template_type":"generic",
      "elements":[
        {
          "title":"Title",
          "buttons":[ {
            "title":"Link 1",
            "url": "http://link1.url"
          },
          {
            "title":"Link 2",
            "url": "http://link2.url"
          }
        ]
      }
    ]
  }
}
}
emit(...)
```

2nd try:
```
message = {
  "attachment":{
    "type":"template",
    "payload":{
      "template_type":"generic",
      "elements":[
        {
          "title":"Title 1",
          "buttons":[ {
            "title":"Link 1",
            "url": "http://link1.url"
          },
        {
          "title":"Title 2",
          "buttons":[ {
            "title":"Link 2",
            "url": "http://link2.url"
          }
        ]
      }
    ]
  }
}
}
emit(...)
```

Somehow I think from the way the keys are named in this payload ("elements", "buttons") it must be possible to send and display multiple...

**Comment by radicand** [comment]
It looks like its hardcoded to one element at the moment: https://github.com/mrbot-ai/rasa-webchat/blob/ad6c44a0823cee81e0e2e331c69e416fba410ce0/src/components/Widget/index.js#L207-L215 . I would also love to see support for multiple items as well.

**Comment by MatthieuJnon** [comment]
Please follow this issue https://github.com/botfront/rasa-webchat/issues/263 for proper documentation of available response types.
