### ISSUE TITLE
(Enhancement) need to integrate speech recognition to the widget

### ISSUE THREAD

**Issue by arcontechnologies** [botfront/rasa-webchat#9]
Hi
I'm not a web developer  but I wonder if it is possible to integrate speech recognition  so that user can choose to chat or speak with the chatbot.

if so how difficult it is to get it up and ready ?

Thanks for your feedback

**Comment by HansaJugnarain** [comment]
Yes, you can easily integrate a speech recognition module in your chatbot. It is not difficult to include, with all the tools available today. You can try the web speech API.

**Comment by MatthieuJnon** [comment]
At this time the speech recognition technologies available on browsers are just not there yet. If someone is willing to propose a PR, we're very open to reviewing it
