### ISSUE TITLE
Conversation initializing on load in Firefox 

### ISSUE THREAD

**Issue by trnc-ck** [botfront/rasa-webchat#94]
The widget works in Chrome and Safari normally. When opening the Conversation, the initPayload gets sent. But on Firefox the initialized param in the storage gets true when the js is loaded and when opening the widget, the initPayload doesn't get sent.

Any ideas?

**Comment by GeovanaRamos** [comment]
We're having the same problem. Sometimes, Firefox throws "transport error" on initPayload while the widget is working fine in Chrome at the same time. It happens randomly and it keeps happening for some time and then it returns to normal by itself.

**Comment by MatthieuJnon** [comment]
I've just tried 50 times in a row with Firefox 68.11.0esr (64-bit) and I could not reproduce a single time. Please let us know if it's still happening
