### ISSUE TITLE
SocketIOInput channel Instructions

### ISSUE THREAD

**Issue by pecatade** [botfront/rasa-webchat#95]
Hi, the SocketIOInput channel instructions link is not working, where can a I find the information?

**Comment by arbazkhan971** [comment]
actually rasa has changed it's docs
use this link to open that pages
https://legacy-docs.rasa.com/docs/core/connectors/#id21

**Comment by mgcostaParedes** [comment]
for all the people who is having trouble on creating the channel at rasa, theres what you need:

1 - go to the credentials.yml and add the following code
`custom_socket.SocketIOInput:
  session_persistence: true`
where the custom_socket is the name of your custom socket channel that u will create, in this example i used the name `custom_socket`

2 - create the channel to connect to the rasa core, the following code is, working and its already sending the customData on metadata of each message. ( will provide an zip with the working code)
 
Hope, it will help someone else who doesnt want to spend a lot of work on trying to get the things working like i did.




[custom_socket.zip](https://github.com/mrbot-ai/rasa-webchat/files/3546895/custom_socket.zip)

**Comment by radicand** [comment]
@mgcostaParedes thanks for sharing this, I adapted it to work using the latest base code from https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/socketio.py . Your code as-is suffers from a CORS bug that was patched in a revision to that file, so for those that follow, use what is provided in the current Rasa repo, and replace the final function only that deals with mapping the customData.

If you intend to use this with Docker, just copy the custom_socket.py file to the /app directory in your Dockerfile, and the do the rest per the above comment regarding credentials. Make sure you don't have the base socketio implementation enabled and use this override instead.

To extract the customData, use something like the below (which extracts the userId). This is hackish and you can't trust this data unless you change it to a JWT or similar. You've been warned.

```py
def getUserId(eventsTracker):
    filtered_events = filter(lambda evt: 'event' in evt and evt['event'] ==
                             'user' and 'metadata' in evt and 'userId' in evt['metadata'], eventsTracker)
    user = list(filtered_events)[0]['metadata']['userId']
    return user

theUser = getUserId(tracker.events)
```

**Comment by sivanandh** [comment]
Hi, 

when i try to add new custom channel i am getting **ModuleNotFoundError: No module named** and **Exception: Failed to find input channel class for 'channel.MyIO.RestInput'** i don't know how to fix these issues. please help me to fix these issue

**Comment by MatthieuJnon** [comment]
Hi, I believe those issues are related to rasa and not the rasa-webchat. Thank you
