### ISSUE TITLE
How to modify or edit this chat bot ? 

### ISSUE THREAD

**Issue by shivangpatel** [botfront/rasa-webchat#96]
I need to change UI colour and some css twik. So, Is there any guide/documentation available for simply edit or modify this app ?

**Comment by nomadus** [comment]
You can change the colors in the separate css file.
`.conversation-container .header {
    background-color: #AAADAE;
  }

.conversation-container .title {
  color:#505C62
}

.launcher {
    background-color: #AAADAE;
}

.conversation-container .client {
    background-color: #AAADAE;
    color:#020001
}`

**Comment by olivierdpn** [comment]
Hello, 
I've got the same problem and I had a new custom css file to change the color of the box of the chatbot but this code changes only the color of the title of the bot... 

Do you have any idea of the parameter and the style to change the color of the chatbot ?

Thanks a lot
Olivier
