### ISSUE TITLE
Hide input text area when bot answers with buttons

### ISSUE THREAD

**Issue by true1337** [botfront/rasa-webchat#98]
Hi, is there any option to hide input area when bot answers with buttons so that a person can’t answer except with the button

**Comment by saurabh-m523** [comment]
I really need this feature, but I don't know react :(

**Comment by n2718281** [comment]
@true1337 @saurabh-m523 I am looking for that too. Did you find a solution? That was discussed also in the rasa forum: https://forum.rasa.com/t/how-to-disable-user-input-option-while-dealing-with-buttons/15308

**Comment by znat** [comment]
It's coming, couple of weeks max

**Comment by gurtajs4** [comment]
@znat  any update here?

**Comment by gurtajs4** [comment]
Rename this to index.js and copy it to  path 
rasa-webchat\src\components\Widget\components\Conversation\components\Messages\components\QuickReply

and compile 
'npm run build' and use the new index.js

[index.txt](https://github.com/botfront/rasa-webchat/files/4396722/index.txt)

**Comment by MatthieuJnon** [comment]
Hi, if you're using the webchat with Botfront, you can disable the input in your response settings in Botfront.

**Comment by ChikkaUdayaSai** [comment]
How can I send a message from Rasa with metadata **userInput: disable**. After sending metadata, do I need to write anything else to re-enable user input?

I am new to this. Can you kindly show me an example?

**Comment by JustineFilion** [comment]
I am using rasa webchat, what is the easiest way to do this?
